package com.dimata.posbo.report.sale;

import com.dimata.posbo.report.purchase.PurchaseOrderPrintPDF;
import com.dimata.posbo.entity.masterdata.MemberReg;
import com.dimata.posbo.entity.masterdata.PstMemberReg;
import com.dimata.posbo.entity.masterdata.Unit;
import com.dimata.posbo.entity.masterdata.PstUnit;
import com.dimata.posbo.session.sales.SessSaleCommision;
import com.dimata.qdep.form.FRMQueryString;
import com.dimata.qdep.form.FRMHandler;
import com.dimata.pos.entity.billing.BillMain;
import com.dimata.pos.entity.billing.PstBillMain;
import com.dimata.pos.entity.billing.PstBillDetail;
import com.dimata.pos.entity.billing.Billdetail;
import com.dimata.util.Formater;
import com.dimata.common.entity.location.Location;
import com.dimata.common.entity.location.PstLocation;
import com.dimata.common.entity.custom.DataCustom;
import com.dimata.common.entity.custom.PstDataCustom;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import java.util.Vector;
import java.awt.*;
import java.io.IOException;
import java.io.ByteArrayOutputStream;

/**
 * Created by IntelliJ IDEA.
 * User: gadnyana
 * Date: Nov 18, 2006
 * Time: 9:53:25 AM
 * To change this template use File | Settings | File Templates.
 */
public class InvoiceInternalConsigmentPDF extends HttpServlet {

    public static final String textHeaderMain[][] =
            {
                {"INVOICE", "Nomor", "Lokasi", "Tanggal", "Supplier", "Nama", "Alamat","Telp","Contact","Keterangan"},
                {"INVOICE", "Number", "From Location", "Date", "Supplier", "Name","Address" ,"Phone","Contact","Description"}
            };

    public static final String textHeaderItem[][] =
            {
                {"No", "Kode", "Nama Barang", "Unit", "Qty", "Harga", "Sub Total"},
                {"No", "Code", "Description", "Unit", "Qty", "Price", "Sub Total"}
            };

    /* Generated by Together */
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
    }

    /** Destroys the servlet.
     */
    public void destroy() {

    }

    public static Vector vect = new Vector();
    // setting the color values
    public static Color border = new Color(0x00, 0x00, 0x00);
    public static Color bgColor = new Color(220, 220, 220);

    // setting some fonts in the color chosen by the user
    public static com.lowagie.text.Font fontTitle = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 13, com.lowagie.text.Font.BOLD, PurchaseOrderPrintPDF.border);
    public static com.lowagie.text.Font fontTitleUnderline = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 13, com.lowagie.text.Font.BOLD + com.lowagie.text.Font.UNDERLINE, PurchaseOrderPrintPDF.border);
    public static com.lowagie.text.Font fontMainHeader = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 10, com.lowagie.text.Font.BOLD, PurchaseOrderPrintPDF.border);
    public static com.lowagie.text.Font fontHeader = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 10, com.lowagie.text.Font.ITALIC, PurchaseOrderPrintPDF.border);
    public static com.lowagie.text.Font fontHeaderUnderline = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 10, com.lowagie.text.Font.ITALIC + com.lowagie.text.Font.UNDERLINE, PurchaseOrderPrintPDF.border);
    public static com.lowagie.text.Font fontListHeader = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 10, com.lowagie.text.Font.BOLD, PurchaseOrderPrintPDF.border);
    public static com.lowagie.text.Font fontLsContent = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 8);
    public static com.lowagie.text.Font fontLsContentUnderline = new com.lowagie.text.Font(com.lowagie.text.Font.TIMES_NEW_ROMAN, 8,com.lowagie.text.Font.UNDERLINE, PurchaseOrderPrintPDF.border);

    /** Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     */

    protected void processRequest(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        Color bgColor = new Color(200, 200, 200);
        com.lowagie.text.Rectangle rectangle = new com.lowagie.text.Rectangle(20, 20, 20, 20);
        rectangle.rotate();
        Document document = new Document(PageSize.A4, 20, 20, 30, 30);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try {
            //step2.2: creating an instance of the writer
            PdfWriter writer = PdfWriter.getInstance(document, baos);
            // step 3.1: adding some metadata to the document
            document.addSubject("This is a subject.");
            document.addSubject("This is a subject two.");

            //HeaderFooter header = new HeaderFooter(new Phrase("This is a header."), false);
            HeaderFooter footer = new HeaderFooter(new Phrase(new Chunk("", PurchaseOrderPrintPDF.fontLsContent)), false);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setBorder(HeaderFooter.NO_BORDER);
            //document.setHeader(header);
            document.setFooter(footer);

            document.open();

            /* get data from session */
            Vector list = new Vector();
            HttpSession sess = request.getSession(true);
            long oidBill = 0;
            int SESS_LANGUAGE = 0;
            String approot = "";
            try {
                SESS_LANGUAGE = FRMQueryString.requestInt(request, "sess_language");
                oidBill = FRMQueryString.requestLong(request, "hidden_bill_main_id");
                approot = FRMQueryString.requestString(request, "approot");
            } catch (Exception e) {
                System.out.println("Exc : " + e.toString());
            }

            BillMain billMain = new BillMain();
            Vector vctContent = new Vector();
            if (oidBill != 0) {
                try {
                    billMain = PstBillMain.fetchExc(oidBill);
                    String where = PstBillDetail.fieldNames[PstBillDetail.FLD_BILL_MAIN_ID]+"="+oidBill;
                    vctContent = PstBillDetail.list(0, 0, where,"");
                } catch (Exception e) {
                    System.out.println("err : " + e.toString());
                }

                String pathImage = "http://"+request.getServerName()+":"+request.getServerPort()+approot+ "/images/company.jpg";
                System.out.println("approot = "+pathImage);
                com.lowagie.text.Image gambar = null;
                try{
                    gambar = com.lowagie.text.Image.getInstance(pathImage);
                }catch(Exception ex){
                    System.out.println("gambar >>>>>> = "+gambar.getImageMask());
                }
                System.out.println("approot 00.1 = "+gambar);
                InvoiceInternalConsigmentPDF.vect = new Vector();
                document.add(InvoiceInternalConsigmentPDF.getHeaderImage(SESS_LANGUAGE,gambar));
                document.add(InvoiceInternalConsigmentPDF.getHeader(SESS_LANGUAGE, billMain));
                InvoiceInternalConsigmentPDF.vect.add("ACCOUNTING");
                 System.out.println("approot = "+gambar);
                document = InvoiceInternalConsigmentPDF.getContent(vctContent, document, writer, SESS_LANGUAGE, billMain);
                document.add(InvoiceInternalConsigmentPDF.getAccountInformation());
                document.add(InvoiceInternalConsigmentPDF.getHeaderApprove(InvoiceInternalConsigmentPDF.vect));
            }
        } catch (Exception e) {
            System.out.println("Exception e : " + e.toString());
        }

        // step 5: closing the document
        document.close();

        // we have written the pdfstream to a ByteArrayOutputStream,
        // now we are going to write this outputStream to the ServletOutputStream
        // after we have set the contentlength (see http://www.lowagie.com/iText/faq.html#msie)
        response.setContentType("application/pdf");
        response.setContentLength(baos.size());
        ServletOutputStream out = response.getOutputStream();
        baos.writeTo(out);
        out.flush();
    }


    /* this method make table header */
    private static Table getHeaderImage(int SESS_LANGUAGE, com.lowagie.text.Image gambar) throws BadElementException, DocumentException {
        Table table = new Table(2);
        try {
            int ctnInt[] = {40, 60};
            table.setBorderColor(new Color(255, 255, 255));
            table.setWidth(100);
            table.setWidths(ctnInt);
            table.setCellpadding(1);
            table.setCellspacing(0);

            //  nama company, alamat,telp
            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            //URL url = new URL("");

            gambar.setAlignment(com.lowagie.text.Image.MIDDLE);
            gambar.scalePercent(40);
            table.addCell(new Phrase(new Chunk(gambar,0,0)));
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][0], InvoiceInternalConsigmentPDF.fontTitleUnderline));

            table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontTitle));

        } catch (Exception e) {
        }
        return table;
    }


    /* this method make table header */
    private static Table getHeader(int SESS_LANGUAGE, BillMain billMain) throws BadElementException, DocumentException {

        if (billMain.getOID() != 0) {

            int ctnInt[] = {10, 3, 39, 15, 3, 30};
            Table table = new Table(6);
            table.setBorderColor(new Color(255, 255, 255));
            table.setWidth(100);
            table.setWidths(ctnInt);
            table.setCellpadding(1);
            table.setCellspacing(0);

            //  nama company, alamat,telp
            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][1], InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(" :", InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(billMain.getInvoiceNumber(), InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase("For Customer", InvoiceInternalConsigmentPDF.fontHeaderUnderline));
            table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontHeader));

            // tanggal transaksi, lokasi tujuan
            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][3], InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(" :", InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(Formater.formatDate(billMain.getBillDate(), "dd-MM-yyyy"), InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][5], InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(" :", InvoiceInternalConsigmentPDF.fontHeader));
            Location locTujuan = new Location();
            MemberReg memberReg = new MemberReg();
            try {
                //locTujuan = PstLocation.fetchExc(billMain.getLocationId());
                memberReg = PstMemberReg.fetchExc(billMain.getCustomerId());
                locTujuan.setName(memberReg.getPersonName());
                locTujuan.setAddress(memberReg.getHomeAddr());
                locTujuan.setTelephone(memberReg.getTelpNr());
                locTujuan.setFax(memberReg.getFax());
                locTujuan.setPerson(memberReg.getPersonName());
            } catch (Exception e) {
            }
            table.addCell(new Phrase(locTujuan.getName(), InvoiceInternalConsigmentPDF.fontHeader));

            // nama sto, alamat tujuan
            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultColspan(3);
            Location loc = new Location();
            try {
                String where = PstLocation.fieldNames[PstLocation.FLD_TYPE]+"="+PstLocation.TYPE_LOCATION_WAREHOUSE;
                Vector vlist = PstLocation.list(0,0,where,"");
                if(vlist!=null && vlist.size()>0){
                    loc = (Location)vlist.get(0);
                }
            } catch (Exception e) {
            }
            table.addCell(new Phrase(loc.getName(), InvoiceInternalConsigmentPDF.fontHeader));
            InvoiceInternalConsigmentPDF.vect.add(loc.getName());

            table.setDefaultColspan(1);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][6], InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(" :", InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(locTujuan.getAddress(), InvoiceInternalConsigmentPDF.fontHeader));

            // Alamat, telp supplier
            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultColspan(3);
            table.addCell(new Phrase(loc.getAddress(), InvoiceInternalConsigmentPDF.fontHeader));

            table.setDefaultColspan(1);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][7], InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(" :", InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(locTujuan.getTelephone()+"/Fax : "+locTujuan.getFax(), InvoiceInternalConsigmentPDF.fontHeader));

            // Telp, Contact supplier
            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultColspan(3);
            table.addCell(new Phrase(loc.getTelephone(), InvoiceInternalConsigmentPDF.fontHeader));

            table.setDefaultColspan(1);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][8], InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(" :", InvoiceInternalConsigmentPDF.fontHeader));
            table.addCell(new Phrase(locTujuan.getPerson(), InvoiceInternalConsigmentPDF.fontHeader));

            return table;
        }

        return new Table(1);
    }


    private static Table getListHeader(int SESS_LANGUAGE) throws BadElementException, DocumentException {
        //int ctnInt[] = {5, 15, 40, /*15,15,*/8,10,/*15,*/15/*,10*/};

        int ctnInt[] = {3, 11, 35, 5, 5, 10, 10};
        //Table table = new Table(10);
        Table table = new Table(7);
        try {
            table.setBorderColor(new Color(255, 255, 255));
            table.setWidth(100);
            table.setWidths(ctnInt);
            table.setBorderWidth(0);
            table.setCellpadding(1);
            table.setCellspacing(1);

            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultCellBackgroundColor(InvoiceInternalConsigmentPDF.bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderItem[SESS_LANGUAGE][0], InvoiceInternalConsigmentPDF.fontListHeader));

            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultCellBackgroundColor(InvoiceInternalConsigmentPDF.bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderItem[SESS_LANGUAGE][1], InvoiceInternalConsigmentPDF.fontListHeader));

            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultCellBackgroundColor(InvoiceInternalConsigmentPDF.bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderItem[SESS_LANGUAGE][2], InvoiceInternalConsigmentPDF.fontListHeader));

            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultCellBackgroundColor(InvoiceInternalConsigmentPDF.bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderItem[SESS_LANGUAGE][3], InvoiceInternalConsigmentPDF.fontListHeader));

            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultCellBackgroundColor(InvoiceInternalConsigmentPDF.bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderItem[SESS_LANGUAGE][4], InvoiceInternalConsigmentPDF.fontListHeader));

            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultCellBackgroundColor(InvoiceInternalConsigmentPDF.bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderItem[SESS_LANGUAGE][5], InvoiceInternalConsigmentPDF.fontListHeader));

            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
            table.setDefaultCellBackgroundColor(InvoiceInternalConsigmentPDF.bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderItem[SESS_LANGUAGE][6], InvoiceInternalConsigmentPDF.fontListHeader));

        } catch (Exception e) {
            System.out.println("exc header" + e.toString());
        }

        return table;
    }

    private static Document getContent(Vector vct, Document document, PdfWriter writer, int SESS_LANGUAGE, BillMain billMain) throws BadElementException, DocumentException {
        Table table = InvoiceInternalConsigmentPDF.getListHeader(SESS_LANGUAGE);
        if (vct != null && vct.size() > 0) {
            try {
                double total = 0;
                double totalQty = 0;
                for (int i = 0; i < vct.size(); i++) {
                    Billdetail  billDetail = (Billdetail)vct.get(i);
                    total += (billDetail.getItemPrice() * billDetail.getQty());

                    table.setDefaultCellBackgroundColor(Color.WHITE);
                    table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
                    table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                    table.addCell(new Phrase(String.valueOf(i + 1), InvoiceInternalConsigmentPDF.fontLsContent));

                    table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
                    table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                    table.addCell(new Phrase(billDetail.getSku(), InvoiceInternalConsigmentPDF.fontLsContent));

                    table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
                    table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                    table.addCell(new Phrase(billDetail.getItemName(), InvoiceInternalConsigmentPDF.fontLsContent));

                    Unit unit = new Unit();
                    try{
                        unit = PstUnit.fetchExc(billDetail.getUnitId());
                    }catch(Exception e){}
                    table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
                    table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                    table.addCell(new Phrase(unit.getCode(), InvoiceInternalConsigmentPDF.fontLsContent));

                    table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
                    table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                    table.addCell(new Phrase(String.valueOf(billDetail.getQty()), InvoiceInternalConsigmentPDF.fontLsContent));
                    totalQty += billDetail.getQty();

                    table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                    table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                    table.addCell(new Phrase(FRMHandler.userFormatStringDecimal(billDetail.getItemPrice()), InvoiceInternalConsigmentPDF.fontLsContent));

                    table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                    table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                    table.addCell(new Phrase(FRMHandler.userFormatStringDecimal(billDetail.getItemPrice() * billDetail.getQty()), InvoiceInternalConsigmentPDF.fontLsContent));

                    /*if (!writer.fitsPage(table)) {
                        table.deleteLastRow();
                        i--;
                        table.deleteLastRow();
                        i--;
                        document.add(table);
                        document.newPage();
                        table = getListHeader(SESS_LANGUAGE);
                    }*/
                }

                // total real
                table.setDefaultCellBackgroundColor(Color.WHITE);
                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.setDefaultColspan(4);
                table.addCell(new Phrase("Rec. Retail", InvoiceInternalConsigmentPDF.fontListHeader));

                table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.setDefaultColspan(1);
                table.addCell(new Phrase(""+totalQty, InvoiceInternalConsigmentPDF.fontLsContent));

                table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontLsContent));

                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.addCell(new Phrase(FRMHandler.userFormatStringDecimal(total), InvoiceInternalConsigmentPDF.fontLsContent));

                Vector vOtherComm = SessSaleCommision.getDataCommision(billMain.getOID());
                DataCustom dataCustomCommOutlet = PstDataCustom.getDataCustom(billMain.getOID(),SessSaleCommision.strNameCommision[SessSaleCommision.COMM_OUTLET]);


                    //total = total - billMain.getDiscount();
                table.setDefaultCellBackgroundColor(Color.WHITE);
                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.setDefaultColspan(4);
                table.addCell(new Phrase("Commision Outlet", InvoiceInternalConsigmentPDF.fontListHeader));

                table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.setDefaultColspan(1);
                table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontLsContent));

                double totComm = (Double.parseDouble(dataCustomCommOutlet.getDataValue())/ total) * 100;
                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.addCell(new Phrase(FRMHandler.userFormatStringDecimal(totComm), InvoiceInternalConsigmentPDF.fontLsContent));

                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.addCell(new Phrase(FRMHandler.userFormatStringDecimal(Double.parseDouble(dataCustomCommOutlet.getDataValue())), InvoiceInternalConsigmentPDF.fontLsContent));

                // total
                table.setDefaultCellBackgroundColor(Color.WHITE);
                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.setDefaultColspan(4);
                table.addCell(new Phrase("Total", InvoiceInternalConsigmentPDF.fontListHeader));

                table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.setDefaultColspan(1);
                table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontLsContent));

                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontLsContent));

                table.setDefaultHorizontalAlignment(Table.ALIGN_RIGHT);
                table.setDefaultVerticalAlignment(Table.ALIGN_MIDDLE);
                table.addCell(new Phrase(FRMHandler.userFormatStringDecimal(total - Double.parseDouble(dataCustomCommOutlet.getDataValue())), InvoiceInternalConsigmentPDF.fontLsContent));

                document.add(table);
                document.add(InvoiceInternalConsigmentPDF.getHeaderLast(SESS_LANGUAGE, billMain, totalQty, total));
            } catch (Exception e) {
                System.out.println("exc contenct" + e.toString());
            }
        }

        return document;
    }


    private static Table getHeaderLast(int SESS_LANGUAGE, BillMain billMain, double totalQty, double total) throws BadElementException, DocumentException {
        int ctnInt[] = {10, 1, 60, 10, 1, 15};
        //Table table = new Table(10);
        Table table = new Table(6);
        try {
            table.setBorderColor(new Color(255, 255, 255));
            table.setWidth(100);
            table.setWidths(ctnInt);
            table.setBorderWidth(0);
            table.setCellpadding(0);
            table.setCellspacing(0);

            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_TOP);
            //table.setDefaultCellBackgroundColor(bgColor);
            table.addCell(new Phrase(InvoiceInternalConsigmentPDF.textHeaderMain[SESS_LANGUAGE][9], InvoiceInternalConsigmentPDF.fontLsContentUnderline));

            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_TOP);
            //table.setDefaultCellBackgroundColor(bgColor);
            table.addCell(new Phrase(":", InvoiceInternalConsigmentPDF.fontLsContent));

            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_TOP);
            table.setDefaultColspan(4);
            table.addCell(new Phrase("", InvoiceInternalConsigmentPDF.fontLsContent));

        } catch (Exception e) {
            System.out.println("exc header" + e.toString());
        }
        return table;
    }

    private static Table getHeaderApprove(Vector vect) throws BadElementException, DocumentException {
        Table table = new Table(vect.size());
        try {
            table.setBorderColor(new Color(255, 255, 255));
            table.setWidth(100);
            table.setBorderWidth(0);
            table.setCellpadding(1);
            table.setCellspacing(1);
            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_CENTER);
            table.setDefaultVerticalAlignment(Table.ALIGN_TOP);
            for (int k = 0; k < vect.size(); k++) {
                table.addCell("");
            }
            for (int k = 0; k < vect.size(); k++) {
                table.addCell(new Phrase(String.valueOf(vect.get(k)), InvoiceInternalConsigmentPDF.fontLsContent));
            }
            for (int k = 0; k < vect.size(); k++) {
                table.addCell("");
                table.addCell("");
            }
            for (int k = 0; k < vect.size(); k++) {
                table.addCell(new Phrase(String.valueOf("(....................................)"), InvoiceInternalConsigmentPDF.fontLsContent));
            }
        } catch (Exception e) {
            System.out.println("exc header" + e.toString());
        }
        return table;
    }

    /**
     * gadnyana
     * @return
     * @throws com.lowagie.text.BadElementException
     * @throws com.lowagie.text.DocumentException
     */
    private static Table getAccountInformation() throws BadElementException, DocumentException {
        Table table = new Table(1);
        try {
            table.setBorderColor(new Color(255, 255, 255));
            table.setAlignment(Table.ALIGN_LEFT);
            table.setWidth(60);
            table.setBorderWidth(0);
            table.setCellpadding(1);
            table.setCellspacing(1);

            String shipping = "";
            try {
                shipping = (String)com.dimata.system.entity.PstSystemProperty.getValueByName("REKENING_ACCOUNT_NUMBER");
            } catch (Exception e) {
                shipping = " ";
            }

            String strShipping = shipping.replaceAll(";", "\n");

            table.setDefaultCellBorder(Table.NO_BORDER);
            table.setDefaultHorizontalAlignment(Table.ALIGN_LEFT);
            table.setDefaultVerticalAlignment(Table.ALIGN_TOP);
            table.addCell(new Phrase(String.valueOf(strShipping), InvoiceInternalConsigmentPDF.fontLsContent));

        } catch (Exception e) {
            System.out.println("exc header" + e.toString());
        }
        return table;
    }

    /** Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     */
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    /** Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     */
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    /** Returns a short description of the servlet.
     */
    public String getServletInfo() {
        return "Short description";
    }
}
