// Generated by Together 

package com.dimata.aiso.entity.masterdata;

// package qdep 
import com.dimata.qdep.entity.*;

public class AccountLink extends Entity
{

    private int linkType;
    private long firstId;
    private long secondId;

    /** Holds value of property departmentOid. */
    private long departmentOid;
    
    public int getLinkType(){ return linkType; }

    public void setLinkType(int linkType){ this.linkType = linkType; }

    public long getFirstId(){ return firstId; }

    public void setFirstId(long firstId){ this.firstId = firstId; }

    public long getSecondId(){ return secondId; }

    public void setSecondId(long secondId){ this.secondId = secondId; }
    
    /** Getter for property departmentOid.
     * @return Value of property departmentOid.
     *
     */
    public long getDepartmentOid() {
        return this.departmentOid;
    }
    
    /** Setter for property departmentOid.
     * @param departmentOid New value of property departmentOid.
     *
     */
    public void setDepartmentOid(long departmentOid) {
        this.departmentOid = departmentOid;
    }
    
}
