/*
 * MemberSearchDialog.java
 *
 * Created on December 17, 2004, 9:31 AM
 */

package com.dimata.pos.cashier;

import com.dimata.ObjLink.BOCashier.CustomerLink;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import com.dimata.posbo.entity.masterdata.*;



/**
 *
 * @author  wpradnyana
 */
public class GuestSearchDialog extends JDialog {
    
    public GuestSearchDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        initAllFields();
        
    }
    public void initAllFields(){
        initButton();
        this.setDataVector(null);
        this.setMemberTableModel(null);
        this.memberListTable.setModel(this.getMemberTableModel());
        cmdSetColumnTableSize();
    }
    
    private void initButton(){
        nextRecordButton.setEnabled(false);
        prevRecordButton.setEnabled(false);
        firstRecordButton.setEnabled(false);
        lastRecordButton.setEnabled(false);
        selectRecordButton.setEnabled(false);
    }
    
    public void cmdSetColumnTableSize(){
        int totalWidth = memberListTable.getWidth();
        memberListTable.getColumnModel().getColumn(COL_NO).setPreferredWidth((int)(totalWidth*0.1));
        memberListTable.getColumnModel().getColumn(COL_NAME).setPreferredWidth((int)(totalWidth*0.5));
        memberListTable.getColumnModel().getColumn(COL_ROOM_NUMBER).setPreferredWidth((int)(totalWidth*0.2));
        memberListTable.getColumnModel().getColumn(COL_RESERV_NUM).setPreferredWidth((int)(totalWidth*0.2));
        memberListTable.repaint();
        memberListTable.revalidate();
    }
    private DefaultTableModel memberTableModel= null;
    //public
    
    private static final int COL_NO=0;
    private static final int COL_NAME=1;
    private static final int COL_ROOM_NUMBER=2;
    private static final int COL_RESERV_NUM=3;
    private static String [] fieldNames={
        "No","Guest Name","Room Number","Reservation Number"
    };
    
    private Vector dataVector = null;
    private Vector columnIdentifier = null;
    public Vector getColumnIdentifier(){
        if(columnIdentifier==null){
            columnIdentifier = new Vector();
            for(int i = 0;i<fieldNames.length;i++){
                columnIdentifier.add(fieldNames[i]);
            }
            
        }
        return columnIdentifier;
    }
    public void setColumnIdentifier(Vector columnIdentifier){
        this.columnIdentifier = columnIdentifier;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberListTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resvNumberTextField = new javax.swing.JTextField();
        guestNameTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        roomNumberTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        firstRecordButton = new javax.swing.JButton();
        prevRecordButton = new javax.swing.JButton();
        nextRecordButton = new javax.swing.JButton();
        lastRecordButton = new javax.swing.JButton();
        selectRecordButton = new javax.swing.JButton();
        closeFrameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guest Search");
        setModal(true);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(new javax.swing.border.TitledBorder(""));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 150));
        memberListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Guest Name", "Room Number", "Reservation Number"
            }
        ));
        memberListTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memberListTableKeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(memberListTable);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(new javax.swing.border.TitledBorder("Keyword"));
        jLabel1.setText("Guest Name");
        jPanel4.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("Reservation Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jLabel2, gridBagConstraints);

        resvNumberTextField.setColumns(10);
        resvNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resvNumberTextFieldActionPerformed(evt);
            }
        });
        resvNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resvNumberTextFieldFocusGained(evt);
            }
        });
        resvNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resvNumberTextFieldKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel4.add(resvNumberTextField, gridBagConstraints);

        guestNameTextField.setColumns(10);
        guestNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestNameTextFieldActionPerformed(evt);
            }
        });
        guestNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                guestNameTextFieldFocusGained(evt);
            }
        });
        guestNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestNameTextFieldKeyPressed(evt);
            }
        });

        jPanel4.add(guestNameTextField, new java.awt.GridBagConstraints());

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jPanel4.add(searchButton, new java.awt.GridBagConstraints());

        roomNumberTextField.setColumns(10);
        roomNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberTextFieldActionPerformed(evt);
            }
        });
        roomNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roomNumberTextFieldFocusGained(evt);
            }
        });
        roomNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roomNumberTextFieldKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel4.add(roomNumberTextField, gridBagConstraints);

        jLabel3.setText("Room Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(jLabel3, gridBagConstraints);

        jPanel2.add(jPanel4, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        firstRecordButton.setText("First");
        firstRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstRecordButtonActionPerformed(evt);
            }
        });

        jPanel6.add(firstRecordButton, new java.awt.GridBagConstraints());

        prevRecordButton.setText("Prev");
        prevRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevRecordButtonActionPerformed(evt);
            }
        });

        jPanel6.add(prevRecordButton, new java.awt.GridBagConstraints());

        nextRecordButton.setText("Next");
        nextRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRecordButtonActionPerformed(evt);
            }
        });

        jPanel6.add(nextRecordButton, new java.awt.GridBagConstraints());

        lastRecordButton.setText("Last");
        lastRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastRecordButtonActionPerformed(evt);
            }
        });

        jPanel6.add(lastRecordButton, new java.awt.GridBagConstraints());

        selectRecordButton.setText("Choose");
        selectRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRecordButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel6.add(selectRecordButton, gridBagConstraints);

        closeFrameButton.setText("Close");
        closeFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFrameButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel6.add(closeFrameButton, gridBagConstraints);

        jPanel3.add(jPanel6);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    private void roomNumberTextFieldKeyPressed (java.awt.event.KeyEvent evt)//GEN-FIRST:event_roomNumberTextFieldKeyPressed
    {//GEN-HEADEREND:event_roomNumberTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            cmdCancel();
        }
    }//GEN-LAST:event_roomNumberTextFieldKeyPressed
    
    private void roomNumberTextFieldFocusGained (java.awt.event.FocusEvent evt)//GEN-FIRST:event_roomNumberTextFieldFocusGained
    {//GEN-HEADEREND:event_roomNumberTextFieldFocusGained
        // TODO add your handling code here:
        roomNumberTextField.selectAll();
    }//GEN-LAST:event_roomNumberTextFieldFocusGained
    
    private void roomNumberTextFieldActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_roomNumberTextFieldActionPerformed
    {//GEN-HEADEREND:event_roomNumberTextFieldActionPerformed
        // TODO add your handling code here:
        if(roomNumberTextField.getText().length()==0){
            resvNumberTextField.requestFocusInWindow();
        }else{
            cmdSearch();
        }
    }//GEN-LAST:event_roomNumberTextFieldActionPerformed
    
    private void resvNumberTextFieldKeyPressed (java.awt.event.KeyEvent evt)//GEN-FIRST:event_resvNumberTextFieldKeyPressed
    {//GEN-HEADEREND:event_resvNumberTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            cmdCancel();
        }
    }//GEN-LAST:event_resvNumberTextFieldKeyPressed
    
    private void guestNameTextFieldKeyPressed (java.awt.event.KeyEvent evt)//GEN-FIRST:event_guestNameTextFieldKeyPressed
    {//GEN-HEADEREND:event_guestNameTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            cmdCancel();
        }
    }//GEN-LAST:event_guestNameTextFieldKeyPressed
    
    private void resvNumberTextFieldFocusGained (java.awt.event.FocusEvent evt)//GEN-FIRST:event_resvNumberTextFieldFocusGained
    {//GEN-HEADEREND:event_resvNumberTextFieldFocusGained
        // TODO add your handling code here:
        roomNumberTextField.selectAll();
    }//GEN-LAST:event_resvNumberTextFieldFocusGained
    
    private void guestNameTextFieldFocusGained (java.awt.event.FocusEvent evt)//GEN-FIRST:event_guestNameTextFieldFocusGained
    {//GEN-HEADEREND:event_guestNameTextFieldFocusGained
        // TODO add your handling code here:
        guestNameTextField.selectAll();
    }//GEN-LAST:event_guestNameTextFieldFocusGained
    
    private void memberListTableKeyPressed (java.awt.event.KeyEvent evt)//GEN-FIRST:event_memberListTableKeyPressed
    {//GEN-HEADEREND:event_memberListTableKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.cmdDoChoose();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            guestNameTextField.requestFocusInWindow();
        }else if(evt.getKeyCode()==KeyEvent.VK_HOME){
            cmdFirst();
        }else if(evt.getKeyCode()==KeyEvent.VK_END){
            cmdLast();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            cmdPrev();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            cmdNext();
        }else if((evt.getKeyCode()==KeyEvent.VK_UP) && (memberListTable.getSelectedRow() == 0)){
            cmdPrev();
        }else if((evt.getKeyCode()==KeyEvent.VK_DOWN)&& (memberListTable.getSelectedRow() == recordToGet-1)){
            cmdNext();
        }
    }//GEN-LAST:event_memberListTableKeyPressed
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        cmdSearch();
    }//GEN-LAST:event_searchButtonActionPerformed
    
    private void resvNumberTextFieldActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_resvNumberTextFieldActionPerformed
    {//GEN-HEADEREND:event_resvNumberTextFieldActionPerformed
        // TODO add your handling code here:
        cmdSearch();
    }//GEN-LAST:event_resvNumberTextFieldActionPerformed
    
    private void lastRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastRecordButtonActionPerformed
        // TODO add your handling code here:
        cmdLast();
    }//GEN-LAST:event_lastRecordButtonActionPerformed
    
    private void nextRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRecordButtonActionPerformed
        // TODO add your handling code here:
        cmdNext();
    }//GEN-LAST:event_nextRecordButtonActionPerformed
    
    private void prevRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevRecordButtonActionPerformed
        // TODO add your handling code here:
        cmdPrev();
    }//GEN-LAST:event_prevRecordButtonActionPerformed
    
    private void cmdNext(){
        this.startRecord = this.startRecord + this.recordToGet;
        if(this.startRecord >= this.sizeRecord){
            //this.startRecord = this.startRecord - this.sizeRecord;
            cmdFirst();
        }
        cmdSearch();
    }
    private void cmdLast(){
        int mdl = this.sizeRecord % this.recordToGet;
        if(mdl>0){
            this.startRecord = this.sizeRecord - mdl;
        }
        else{
            this.startRecord = this.sizeRecord - this.recordToGet;
        }
        cmdSearch();
    }
    private void cmdPrev(){
        this.startRecord = this.startRecord - this.recordToGet;
        if(this.startRecord<1){
            this.startRecord = 0;
        }
        cmdSearch();
    }
    private void cmdFirst(){
        this.startRecord = 0;
        cmdSearch();
    }
    private void firstRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstRecordButtonActionPerformed
        // TODO add your handling code here:
        cmdFirst();
    }//GEN-LAST:event_firstRecordButtonActionPerformed
    
    private void closeFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFrameButtonActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showConfirmDialog(this,"Are y"
        cmdClose();
    }//GEN-LAST:event_closeFrameButtonActionPerformed
    
    private void cmdClose(){
        CashSaleController.setGuestChoosen(null);
        this.startRecord=0;
        this.dispose();
    }
    private void cmdCancel(){
        cmdClose();
        
    }
    private void guestNameTextFieldActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_guestNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_guestNameTextFieldActionPerformed
        // TODO add your handling code here:
        if(guestNameTextField.getText().length()==0){
            roomNumberTextField.requestFocusInWindow();
        }else{
            cmdSearch();
        }
    }//GEN-LAST:event_guestNameTextFieldActionPerformed
    
    private int startRecord=0;
    private int recordToGet=8;
    private int sizeRecord = 0;
    
    private void refreshButton(int start, int totalRows, int recordToGet){
        
        if(totalRows>0)
            selectRecordButton.setEnabled(true);
        else
            selectRecordButton.setEnabled(false);
        
        if((totalRows - start) <= recordToGet){
            lastRecordButton.setEnabled(false);
            nextRecordButton.setEnabled(false);
        }
        else{
            lastRecordButton.setEnabled(true);
            nextRecordButton.setEnabled(true);
        }
        
        if(start == 0){
            firstRecordButton.setEnabled(false);
            prevRecordButton.setEnabled(false);
        }
        else{
            firstRecordButton.setEnabled(true);
            prevRecordButton.setEnabled(true);
        }
        
    }
    
    public void cmdSearch(){
        Vector result = new Vector();
        
        result =  CashSaleController.getGuestList(guestNameTextField.getText(),roomNumberTextField.getText(),resvNumberTextField.getText(),this.startRecord,this.recordToGet);
        this.sizeRecord = CashSaleController.getCountGuest(guestNameTextField.getText(),roomNumberTextField.getText(),resvNumberTextField.getText(),0,0);
        refreshButton(startRecord, sizeRecord, recordToGet);
        
        dataVector = this.transformResult(result);
        memberTableModel.setDataVector(dataVector,this.getColumnIdentifier());
        memberListTable.requestFocusInWindow();
        if(result.size()>0){
            cmdSetColumnTableSize();
            this.memberListTable.setRowSelectionInterval(0,0);
        }else if(result.size()==0){
            JOptionPane.showMessageDialog(this,"Guest Not found","Search result",JOptionPane.OK_OPTION);
            guestNameTextField.requestFocusInWindow();
        }
        
    }
    private Hashtable hashRowIndexOID = new Hashtable();
    
    private Vector transformResult(Vector raw){
        int rawSize = raw.size();
        Vector fix = new Vector();
        String forDate = CashierMainApp.getDSJ_CashierXML().getConfig(0).fordate;
        for(int i=0;i<rawSize;i++){
            //com.dimata.posbo.entity.masterdata.MemberReg obj = (com.dimata.posbo.entity.masterdata.MemberReg)raw.get(i);
            CustomerLink customer = (CustomerLink)raw.get(i);
            Vector temp = new Vector();
            
            
            hashRowIndexOID.put(new Integer(i),customer);
            temp.add(String.valueOf(this.startRecord+i+1));
            temp.add(customer.getCustomerName());
            temp.add(customer.getRoomNumber());
            temp.add(customer.getResNumber());
            
            fix.add(temp);
        }
        return fix;
    }
    private void selectRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRecordButtonActionPerformed
        // TODO add your handling code here:
        cmdDoChoose();
    }//GEN-LAST:event_selectRecordButtonActionPerformed
    public void cmdDoChoose(){
        Vector guest = new Vector();
        //com.dimata.posbo.entity.masterdata.MemberReg memberReg = new com.dimata.posbo.entity.masterdata.MemberReg();
        int a = memberListTable.getSelectedRow();
        //Vector set = (Vector) this.getHashRowIndexOID().get(new Integer(a));
        CustomerLink customer = (CustomerLink) this.getHashRowIndexOID().get(new Integer(a));
        //CustomerLink customer = (CustomerLink) set.get(0);
        //MemberRegistrationHistory regist = (MemberRegistrationHistory) set.get(1);
        /*try{
            memberReg = com.dimata.posbo.entity.masterdata.PstMemberReg.fetchExc (OID.longValue ());
        }catch(com.dimata.qdep.db.DBException dbe){
         
            dbe.printStackTrace ();
        }*/
        //if(PstMemberReg.isStatusStillValid (regist.getValidExpiredDate ())) {
        guest.add(customer);
        CashSaleController.setGuestChoosen(guest);
        this.startRecord=0;
        this.dispose();
        //}else{
        //   JOptionPane.showMessageDialog (this,"Cannot using this member on transaction (expired)!,\n Please register.","Expired",JOptionPane.ERROR_MESSAGE);
        //guestNameTextField.requestFocusInWindow ();
        //closeFrameButton.requestFocusInWindow ();
        //}
        
        //return new Vector(1,1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new GuestSearchDialog(new JFrame(), true).show();
    }
    
    /**
     * Getter for property memberTableModel.
     * @return Value of property memberTableModel.
     */
    public DefaultTableModel getMemberTableModel() {
        if(memberTableModel==null){
            memberTableModel = new DefaultTableModel();
            memberTableModel.setDataVector(this.getDataVector(),this.getColumnIdentifier());
        }
        return memberTableModel;
    }
    
    /**
     * Setter for property memberTableModel.
     * @param memberTableModel New value of property memberTableModel.
     */
    public void setMemberTableModel(DefaultTableModel memberTableModel) {
        this.memberTableModel = memberTableModel;
    }
    
    /**
     * Getter for property dataVector.
     * @return Value of property dataVector.
     */
    public Vector getDataVector() {
        if(dataVector==null){
            dataVector = new Vector();
        }
        return dataVector;
    }
    
    /**
     * Setter for property dataVector.
     * @param dataVector New value of property dataVector.
     */
    public void setDataVector(Vector dataVector) {
        this.dataVector = dataVector;
    }
    
    /**
     * Getter for property hashRowIndexOID.
     * @return Value of property hashRowIndexOID.
     */
    public Hashtable getHashRowIndexOID() {
        return hashRowIndexOID;
    }
    
    /**
     * Setter for property hashRowIndexOID.
     * @param hashRowIndexOID New value of property hashRowIndexOID.
     */
    public void setHashRowIndexOID(Hashtable hashRowIndexOID) {
        this.hashRowIndexOID = hashRowIndexOID;
    }
    
    /**
     * Getter for property startRecord.
     * @return Value of property startRecord.
     */
    public int getStartRecord() {
        return startRecord;
    }
    
    /**
     * Setter for property startRecord.
     * @param startRecord New value of property startRecord.
     */
    public void setStartRecord(int startRecord) {
        this.startRecord = startRecord;
    }
    
    /**
     * Getter for property recordToGet.
     * @return Value of property recordToGet.
     */
    public int getRecordToGet() {
        return recordToGet;
    }
    
    /**
     * Setter for property recordToGet.
     * @param recordToGet New value of property recordToGet.
     */
    public void setRecordToGet(int recordToGet) {
        this.recordToGet = recordToGet;
    }
    
    /**
     * Getter for property sizeRecord.
     * @return Value of property sizeRecord.
     */
    public int getSizeRecord() {
        return sizeRecord;
    }
    
    /**
     * Setter for property sizeRecord.
     * @param sizeRecord New value of property sizeRecord.
     */
    public void setSizeRecord(int sizeRecord) {
        this.sizeRecord = sizeRecord;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeFrameButton;
    private javax.swing.JButton firstRecordButton;
    private javax.swing.JTextField guestNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastRecordButton;
    private javax.swing.JTable memberListTable;
    private javax.swing.JButton nextRecordButton;
    private javax.swing.JButton prevRecordButton;
    private javax.swing.JTextField resvNumberTextField;
    private javax.swing.JTextField roomNumberTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton selectRecordButton;
    // End of variables declaration//GEN-END:variables
    
}
