/*
 * RestoreAllData.java
 *
 * Created on March 17, 2005, 11:21 AM
 */

package com.dimata.pos.cashier;

import com.dimata.posbo.session.transferdata.TransMasterdata;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  yogi
 */
//public class RestoreMasterdata extends javax.swing.JFrame {
public class RestoreMasterdata extends JDialog {
    
    public static String PATH_DATA_OUT = "C:/data_out/";
    public static String PATH_DATA_IN = "C:/data_in/";
    public static String PATH_MYSQL = "C:/mysql/bin/";
    public int language = 1;
    public static String PROP_DATA_OUT = "data.out";
    public static String PROP_DATA_IN = "data.in";
    public static String PROP_MYSQL = "mysql";
    public static String[] table_names =
     {"pos_material_temp","contact_list_temp"};
    
    /** Creates new form RestoreAllData */
    public RestoreMasterdata() {
        initComponents();
        jButton1.requestFocusInWindow();
    }
    
    public RestoreMasterdata(JFrame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        jButton1.requestFocusInWindow();
    }
    
     /* method to get path data */
    public void getPathData(){
         PATH_DATA_OUT = TransferAllData.getProperties(PROP_DATA_OUT);
         PATH_DATA_IN = TransferAllData.getProperties(PROP_DATA_IN);
         PATH_MYSQL = TransferAllData.getProperties(PROP_MYSQL);
    }
    
    /* method for restore */
    public void restoreData(){
        getPathData();
        TransMasterdata transferMasterdata = new TransMasterdata(table_names,PATH_MYSQL,PATH_DATA_OUT,PATH_DATA_IN);
        int result = transferMasterdata.restoreInClient();
        String msg = transferMasterdata.statusNames[language][result];
        JOptionPane.showMessageDialog(this,msg,"Restore result",JOptionPane.OK_OPTION);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restore");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.setBorder(new javax.swing.border.TitledBorder(null, "Restore Masterdata", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtnSearch.jpg")));
        jButton1.setToolTipText("Press enter to begin restore. Press ESC to exit.");
        jButton1.setLabel("Restore");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // Add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            restoreData();            
        }
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            //System.exit(0);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        restoreData();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new RestoreMasterdata().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
