/*
 * SupervisorLoginDialog.java
 *
 * Created on March 28, 2006, 10:33 AM
 */

package com.dimata.pos.cashier;

import com.dimata.posbo.entity.admin.AppUser;
import com.dimata.posbo.entity.admin.PstAppUser;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author  pulantara
 */
public class SupervisorLoginDialog extends javax.swing.JDialog {
    
    /** Creates new form SupervisorLoginDialog */
    public SupervisorLoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private void cmdLogin(){
        AppUser objUser = new AppUser();
        objUser = PstAppUser.getByLoginIDAndPassword(userNameTextField.getText(), String.copyValueOf(uPasswordField.getPassword()));
        if (objUser == null || objUser.getLoginId().length()==0 || objUser.getLoginId()==null){
            JOptionPane.showMessageDialog(this,"Can't Login, check your User ID and Password","Supervisor Login",JOptionPane.OK_OPTION);
            userNameTextField.requestFocusInWindow();
        }
        else{
            if(objUser.getUserGroupNew()==PstAppUser.GROUP_SUPERVISOR) {
                CashSaleController.setSupervisorApprove(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,"Unauthorized user(supervisor only)","Supervisor Login",JOptionPane.OK_CANCEL_OPTION);
                userNameTextField.requestFocusInWindow();
            }
        }
    }
    
    public void getGlobalKeyListener(KeyEvent evt){
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F1 :
                break;
            case KeyEvent.VK_F2:
                break;
            case KeyEvent.VK_F3:
                break;
            case KeyEvent.VK_F4:
                break;
            case KeyEvent.VK_F5:
                break;
            case KeyEvent.VK_F6:
                break;
            case KeyEvent.VK_F7:
                break;
            case KeyEvent.VK_F8:
                break;
            case KeyEvent.VK_F9:
                break;
            case KeyEvent.VK_F10:
                break;
            case KeyEvent.VK_F11:
                break;
            case KeyEvent.VK_F12:
                break;
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                break;
            case KeyEvent.VK_DOWN:
                break;
            case KeyEvent.VK_UP:
                break;
            case KeyEvent.VK_LEFT:
                break;
            case KeyEvent.VK_RIGHT:
                break;
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_TAB:
                break;
            default:
                break;
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        loginPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        uPasswordField = new javax.swing.JPasswordField();
        cancelLoginButton = new javax.swing.JButton();
        okLoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supervisor Approval Dialog");
        loginPanel.setLayout(new java.awt.GridBagLayout());

        loginPanel.setBorder(new javax.swing.border.TitledBorder(""));
        jLabel7.setText("Supervisor Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        loginPanel.add(jLabel7, gridBagConstraints);

        userNameTextField.setColumns(10);
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        userNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameTextFieldKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 7, 5, 5);
        loginPanel.add(userNameTextField, gridBagConstraints);

        jLabel8.setText("Supervisor Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        loginPanel.add(jLabel8, gridBagConstraints);

        uPasswordField.setColumns(10);
        uPasswordField.setPreferredSize(new java.awt.Dimension(81, 20));
        uPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uPasswordFieldActionPerformed(evt);
            }
        });
        uPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uPasswordFieldKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 7, 5, 5);
        loginPanel.add(uPasswordField, gridBagConstraints);

        cancelLoginButton.setMnemonic('C');
        cancelLoginButton.setText("Cancel ");
        cancelLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLoginButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        loginPanel.add(cancelLoginButton, gridBagConstraints);

        okLoginButton.setIcon(new javax.swing.ImageIcon(""));
        okLoginButton.setMnemonic('L');
        okLoginButton.setText("Approve");
        okLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okLoginButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        loginPanel.add(okLoginButton, gridBagConstraints);

        getContentPane().add(loginPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void cancelLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLoginButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancelLoginButtonActionPerformed

    private void okLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okLoginButtonActionPerformed
        cmdLogin();
    }//GEN-LAST:event_okLoginButtonActionPerformed

    private void uPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uPasswordFieldKeyPressed
        this.getGlobalKeyListener(evt);
    }//GEN-LAST:event_uPasswordFieldKeyPressed

    private void userNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTextFieldKeyPressed
        this.getGlobalKeyListener(evt);
    }//GEN-LAST:event_userNameTextFieldKeyPressed

    private void uPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uPasswordFieldActionPerformed
        okLoginButton.requestFocusInWindow();
        cmdLogin();
    }//GEN-LAST:event_uPasswordFieldActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        uPasswordField.requestFocusInWindow();
    }//GEN-LAST:event_userNameTextFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new SupervisorLoginDialog(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelLoginButton;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton okLoginButton;
    private javax.swing.JPasswordField uPasswordField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
    
}
