/* Generated by Together */

package com.dimata.aiso.form.periode;

/* package servlet */
import javax.servlet.*;
import javax.servlet.http.*;

/* package qdep */
import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;

/* package aiso */
import com.dimata.aiso.entity.periode.*; 

public class FrmPeriode  extends FRMHandler implements I_FRMInterface, I_FRMType
{
    public static final String FRM_PERIODE = "PERIODE";

    public static final int FRM_TGLAWAL            = 0;
    public static final int FRM_TGLAKHIR           = 1;
    public static final int FRM_NAMA               = 2;
    public static final int FRM_KETERANGAN         = 3;
    public static final int FRM_POSTED             = 4;
    public static final int FRM_TGLAKHIRENTRY      = 5;

    public static String[] fieldNames = {
        "TGL_AWAL",
        "TGL_AKHIR",
        "NAMA",
        "KETERANGAN",
        "POSTED",
        "TGL_AKHIR_ENTRY"
    };
    
    public static int[] fieldTypes = {
        TYPE_DATE,
        TYPE_DATE,
        TYPE_STRING + ENTRY_REQUIRED,
        TYPE_STRING,
        TYPE_INT,
        TYPE_DATE + ENTRY_REQUIRED
    };

    private Periode periode;

    public FrmPeriode(Periode periode){
        this.periode = periode;
    }
    
    public FrmPeriode(HttpServletRequest request, Periode periode) {
        super(new FrmPeriode(periode), request);
        this.periode = periode;
    }

    public String getFormName() {
        return FRM_PERIODE;
    }    
    
    public int[] getFieldTypes() {
        return fieldTypes;
    }    
    
    public String[] getFieldNames() {
        return fieldNames;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public Periode getEntityObject() { 
        return periode;
    }

    public void requestEntityObject(Periode periode) {
        try {
            this.requestParam();
            periode.setTglAwal(this.getDate(FRM_TGLAWAL));
            periode.setTglAkhir(this.getDate(FRM_TGLAKHIR));
            periode.setNama(this.getString(FRM_NAMA));
            periode.setKeterangan(this.getString(FRM_KETERANGAN));
            periode.setPosted(PstPeriode.PERIOD_OPEN);
            periode.setTglAkhirEntry(this.getDate(FRM_TGLAKHIRENTRY));
            this.periode = periode;
        } catch(Exception e) {
            periode = new Periode();
        }       
    }
}
