/* Generated by Together */

package com.dimata.aiso.form.masterdata;

import com.dimata.aiso.entity.masterdata.*;
import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;

import javax.servlet.http.HttpServletRequest;

public class FrmAktivaGroup extends FRMHandler implements I_FRMInterface, I_FRMType {
    public static final String FRM_AKTIVA_GROUP = "FRM_AKTIVA_GROUP";
    public static final int FRM_KODE = 0;
    public static final int FRM_NAME = 1;

    public static String[] fieldNames =
            {
                "FRM_KODE",
                "FRM_NAME"
            };

    public static int[] fieldTypes =
            {
                TYPE_STRING + ENTRY_REQUIRED,
                TYPE_STRING + ENTRY_REQUIRED
            };

    private AktivaGroup aktiva;

    public FrmAktivaGroup(AktivaGroup aktiva) {
        this.aktiva = aktiva;
    }

    public FrmAktivaGroup(HttpServletRequest request, AktivaGroup aktiva) {
        super(new FrmAktivaGroup(aktiva), request);
        this.aktiva = aktiva;
    }

    public String getFormName() {
        return FRM_AKTIVA_GROUP;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public AktivaGroup getEntityObject() {
        return aktiva;
    }

    public void requestEntityObject(AktivaGroup aktiva) {
        try {
            this.requestParam();
            aktiva.setKode(this.getString(FRM_KODE));
            aktiva.setNama(this.getString(FRM_NAME));

            this.aktiva = aktiva;
        } catch (Exception e) {
            aktiva = new AktivaGroup();
        }
    }
}
