/* Generated by Together */

package com.dimata.qdep.entity;



public interface I_PersintentExc
{
	public long fetchExc(Entity ent) throws Exception;
  	public long updateExc(Entity ent) throws Exception;
	public long deleteExc(Entity ent) throws Exception;
	public long insertExc(Entity ent) throws Exception;
}