// Generated by Together

package com.dimata.aiso.entity.aktiva;

// package qdep

import com.dimata.qdep.entity.*;

public class PenyusutanAktiva extends Entity {

    private long periodeId = 0;
    private long aktivaId = 0;
    private double value_pny = 0.0;

    public long getPeriodeId() {
        return periodeId;
    }

    public void setPeriodeId(long periodeId) {
        this.periodeId = periodeId;
    }

    public long getAktivaId() {
        return aktivaId;
    }

    public void setAktivaId(long aktivaId) {
        this.aktivaId = aktivaId;
    }

    public double getValue_pny() {
        return value_pny;
    }

    public void setValue_pny(double value_pny) {
        this.value_pny = value_pny;
    }
}