// Generated by Together

package com.dimata.aiso.entity.aktiva;

import com.dimata.aiso.db.*;
import com.dimata.aiso.entity.masterdata.PstAktiva;
import com.dimata.aiso.entity.masterdata.Aktiva;
import com.dimata.aiso.entity.masterdata.PstModulAktiva;
import com.dimata.qdep.entity.I_PersintentExc;
import com.dimata.qdep.entity.Entity;

import java.util.Vector;
import java.util.Date;
import java.sql.ResultSet;

public class PstOrderAktivaItem extends DBHandler implements I_DBInterface, I_DBType, I_PersintentExc {

    public static final String TBL_ORDER_AKTIVA_ITEM = "aiso_aktiva_order_item";
    public static final int FLD_ORDER_AKTIVA_ITEM_ID = 0;
    public static final int FLD_AKTIVA_ID = 1;
    public static final int FLD_ORDER_AKTIVA_ID = 2;
    public static final int FLD_QTY = 3;
    public static final int FLD_PRICE = 4;
    public static final int FLD_TOTAL_PRICE = 5;

    public static String[] fieldNames = {
        "ORDER_AKTIVA_ITEM_ID",
        "AKTIVA_ID",
        "ORDER_AKTIVA_ID",
        "QTY",
        "PRICE",
        "TOTAL_PRICE"
    };

    public static int[] fieldTypes = {
        TYPE_PK + TYPE_ID + TYPE_LONG,
        TYPE_LONG,
        TYPE_LONG,
        TYPE_INT,
        TYPE_FLOAT,
        TYPE_FLOAT

    };

    public PstOrderAktivaItem() {
    }

    public PstOrderAktivaItem(int i) throws DBException {
        super(new PstOrderAktivaItem());
    }

    public PstOrderAktivaItem(String sOid) throws DBException {
        super(new PstOrderAktivaItem(0));
        if (!locate(sOid))
            throw new DBException(this, DBException.RECORD_NOT_FOUND);
        else
            return;
    }

    public PstOrderAktivaItem(long lOid) throws DBException {
        super(new PstOrderAktivaItem(0));
        String sOid = "0";
        try {
            sOid = String.valueOf(lOid);
        } catch (Exception e) {
            throw new DBException(this, DBException.RECORD_NOT_FOUND);
        }

        if (!locate(sOid))
            throw new DBException(this, DBException.RECORD_NOT_FOUND);
        else
            return;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public String getTableName() {
        return TBL_ORDER_AKTIVA_ITEM;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String getPersistentName() {
        return new PstOrderAktivaItem().getClass().getName();
    }

    public long fetchExc(Entity ent) throws DBException {
        OrderAktivaItem aktiva = fetchExc(ent.getOID());
        ent = (Entity) aktiva;
        return aktiva.getOID();
    }

    public long insertExc(Entity ent) throws DBException {
        return insertExc((OrderAktiva) ent);
    }

    public long updateExc(Entity ent) throws DBException {
        return updateExc((OrderAktiva) ent);
    }

    public long deleteExc(Entity ent) throws DBException {
        if (ent == null) {
            throw  new DBException(this, DBException.RECORD_NOT_FOUND);
        }
        return deleteExc(ent.getOID());
    }

    public static OrderAktivaItem fetchExc(long Oid) throws DBException {
        try {
            OrderAktivaItem aktiva = new OrderAktivaItem();
            PstOrderAktivaItem pstAktiva = new PstOrderAktivaItem(Oid);
            aktiva.setOID(Oid);

            aktiva.setOrderAktivaId(pstAktiva.getlong(FLD_AKTIVA_ID));
            aktiva.setQty(pstAktiva.getInt(FLD_QTY));
            aktiva.setPriceOrder(pstAktiva.getlong(FLD_PRICE));
            aktiva.setTotalPriceOrder(pstAktiva.getdouble(FLD_TOTAL_PRICE));

            return aktiva;
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstOrderAktivaItem(0), DBException.UNKNOWN);
        }
    }

    public static long insertExc(OrderAktivaItem aktiva) throws DBException {
        try {
            PstOrderAktivaItem pstAktiva = new PstOrderAktivaItem(0);

            pstAktiva.setLong(FLD_AKTIVA_ID, aktiva.getAktivaId());
            pstAktiva.setLong(FLD_ORDER_AKTIVA_ID, aktiva.getOrderAktivaId());
            pstAktiva.setInt(FLD_QTY, aktiva.getQty());
            pstAktiva.setDouble(FLD_PRICE, aktiva.getPriceOrder());
            pstAktiva.setDouble(FLD_TOTAL_PRICE, aktiva.getTotalPriceOrder());

            pstAktiva.insert();
            aktiva.setOID(pstAktiva.getlong(FLD_ORDER_AKTIVA_ID));
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstOrderAktivaItem(0), DBException.UNKNOWN);
        }
        return aktiva.getOID();
    }

    public static long updateExc(OrderAktivaItem aktiva) throws DBException {
        try {
            if (aktiva != null && aktiva.getOID() != 0) {
                PstOrderAktivaItem pstAktiva = new PstOrderAktivaItem(aktiva.getOID());

                pstAktiva.setLong(FLD_AKTIVA_ID, aktiva.getAktivaId());
                pstAktiva.setLong(FLD_ORDER_AKTIVA_ID, aktiva.getOrderAktivaId());
                pstAktiva.setInt(FLD_QTY, aktiva.getQty());
                pstAktiva.setDouble(FLD_PRICE, aktiva.getPriceOrder());
                pstAktiva.setDouble(FLD_TOTAL_PRICE, aktiva.getTotalPriceOrder());

                pstAktiva.update();
                return aktiva.getOID();
            }
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstOrderAktivaItem(0), DBException.UNKNOWN);
        }
        return 0;
    }

    public static long deleteExc(long Oid) throws DBException {
        try {
            PstOrderAktivaItem pstAktiva = new PstOrderAktivaItem(Oid);
            pstAktiva.delete();
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstOrderAktivaItem(0), DBException.UNKNOWN);
        }
        return Oid;
    }

    public static Vector list(int limitStart, int recordToGet, String whereClause, String order) {
        Vector lists = new Vector();
        DBResultSet dbrs = null;
        try {
            String sql = "SELECT * FROM " + TBL_ORDER_AKTIVA_ITEM + " ";
            if (whereClause != null && whereClause.length() > 0)
                sql = sql + " WHERE " + whereClause;

            if (order != null && order.length() > 0)
                sql = sql + " ORDER BY " + order;

            switch (DBHandler.DBSVR_TYPE) {
                case DBHandler.DBSVR_MYSQL:
                    if (limitStart == 0 && recordToGet == 0)
                        sql = sql + "";
                    else
                        sql = sql + " LIMIT " + limitStart + "," + recordToGet;
                    break;

                case DBHandler.DBSVR_POSTGRESQL:
                    if (limitStart == 0 && recordToGet == 0)
                        sql = sql + "";
                    else
                        sql = sql + " LIMIT " + recordToGet + " OFFSET " + limitStart;

                    break;

                case DBHandler.DBSVR_SYBASE:
                    break;

                case DBHandler.DBSVR_ORACLE:
                    break;

                case DBHandler.DBSVR_MSSQL:
                    break;

                default:
                    break;
            }

            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();

            while (rs.next()) {
                OrderAktivaItem aktiva = new OrderAktivaItem();
                resultToObject(rs, aktiva);
                lists.add(aktiva);
            }
        } catch (Exception error) {
            System.out.println(".:: " + new PstOrderAktivaItem().getClass().getName() + ".list() : " + error.toString());
        } finally {
            DBResultSet.close(dbrs);
        }
        return lists;
    }

    private static void resultToObject(ResultSet rs, OrderAktivaItem aktiva) {
        try {
            aktiva.setOID(rs.getLong(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_ORDER_AKTIVA_ITEM_ID]));
            aktiva.setOrderAktivaId(rs.getLong(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_ORDER_AKTIVA_ID]));
            aktiva.setAktivaId(rs.getLong(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_AKTIVA_ID]));
            aktiva.setQty(rs.getInt(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_QTY]));
            aktiva.setPriceOrder(rs.getDouble(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_PRICE]));
            aktiva.setTotalPriceOrder(rs.getDouble(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_TOTAL_PRICE]));

        } catch (Exception e) {
            System.out.println("resultToObject() " + e.toString());
        }
    }

    public static int getCount(String whereClause) {
        DBResultSet dbrs = null;
        try {
            String sql = "SELECT COUNT(" + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_ORDER_AKTIVA_ID] + ") " +
                    " FROM " + TBL_ORDER_AKTIVA_ITEM;
            if (whereClause != null && whereClause.length() > 0)
                sql = sql + " WHERE " + whereClause;

            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();

            int count = 0;
            while (rs.next()) {
                count = rs.getInt(1);
            }
            rs.close();
            return count;
        } catch (Exception e) {
            System.out.println(e);
            return 0;
        } finally {
            DBResultSet.close(dbrs);
        }
    }


    /** gadnyana
     * mencari list item berdasarkan oid main (order aktiva)
     * @param oidOrderAktiva
     * @return
     */
    public static Vector getListItem(long oidOrderAktiva) {
        Vector lists = new Vector();
        DBResultSet dbrs = null;
        try {
            String sql = "SELECT " +
                    " IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_ORDER_AKTIVA_ITEM_ID] +
                    " ,IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_QTY] +
                    " ,IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_PRICE] +
                    " ,IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_TOTAL_PRICE] +
                    " ,IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_AKTIVA_ID] +
                    " ,MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_KODE] +
                    " ,MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_NAME] +
                    " FROM " + TBL_ORDER_AKTIVA_ITEM + " AS IT " +
                    " INNER JOIN " + PstOrderAktiva.TBL_ORDER_AKTIVA + " AS OD " +
                    " ON IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_ORDER_AKTIVA_ID] +
                    " = OD." + PstOrderAktiva.fieldNames[PstOrderAktiva.FLD_ORDER_AKTIVA_ID] +
                    " INNER JOIN " + PstModulAktiva.TBL_AKTIVA + " AS MA " +
                    " ON IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_AKTIVA_ID] +
                    " = MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_AKTIVA_ID] +
                    " WHERE OD." + PstOrderAktiva.fieldNames[PstOrderAktiva.FLD_ORDER_AKTIVA_ID] + "=" + oidOrderAktiva +
                    " ORDER BY MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_KODE];
            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            System.out.println(sql);
            while (rs.next()) {
                OrderAktivaItem orderAktivaItem = new OrderAktivaItem();
                Aktiva aktiva = new Aktiva();
                Vector vect = new Vector();

                orderAktivaItem.setOID(rs.getLong(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_ORDER_AKTIVA_ITEM_ID]));
                orderAktivaItem.setQty(rs.getInt(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_QTY]));
                orderAktivaItem.setPriceOrder(rs.getDouble(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_PRICE]));
                orderAktivaItem.setTotalPriceOrder(rs.getDouble(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_TOTAL_PRICE]));
                orderAktivaItem.setAktivaId(rs.getLong(PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_AKTIVA_ID]));
                vect.add(orderAktivaItem);

                aktiva.setKode(rs.getString(PstModulAktiva.fieldNames[PstModulAktiva.FLD_KODE]));
                aktiva.setNama(rs.getString(PstModulAktiva.fieldNames[PstModulAktiva.FLD_NAME]));
                vect.add(aktiva);

                lists.add(vect);
            }
        } catch (Exception error) {
            System.out.println(".:: " + new PstOrderAktivaItem().getClass().getName() + ".list() : " + error.toString());
        } finally {
            DBResultSet.close(dbrs);
        }
        return lists;
    }


    /** gadnyana
     * untuk mencvari total order berdasarkan oid order
     * @return
     */
    public static double getTotalOrderAktivaItem(long oidOrderAktiva) {
        DBResultSet dbrs = null;
        double total = 0.0;
        try {
            String sql = "SELECT " +
                    " SUM(IT." + PstOrderAktivaItem.fieldNames[PstOrderAktivaItem.FLD_TOTAL_PRICE] + ")" +
                    " FROM " + TBL_ORDER_AKTIVA_ITEM + " AS IT " +
                    " WHERE IT." + PstOrderAktiva.fieldNames[PstOrderAktiva.FLD_ORDER_AKTIVA_ID] + "=" + oidOrderAktiva;
            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            while (rs.next()) {
                total = rs.getDouble(1);
            }
        } catch (Exception error) {
            System.out.println(".:: " + new PstOrderAktivaItem().getClass().getName() + ".list() : " + error.toString());
        } finally {
            DBResultSet.close(dbrs);
        }
        return total;
    }
}
