// Generated by Together

package com.dimata.aiso.entity.aktiva;

import com.dimata.aiso.db.*;
import com.dimata.aiso.entity.masterdata.Aktiva;
import com.dimata.aiso.entity.masterdata.PstModulAktiva;
import com.dimata.aiso.entity.masterdata.ModulAktiva;
import com.dimata.qdep.entity.I_PersintentExc;
import com.dimata.qdep.entity.Entity;

import java.sql.Connection;
import java.util.Vector;
import java.sql.ResultSet;

public class PstReceiveAktivaItem extends DBHandler implements I_DBInterface,
        I_DBType, I_PersintentExc {

    public static final String TBL_RECEIVE_AKTIVA_ITEM = "aiso_aktiva_receive_item";
    public static final int FLD_RECEIVE_AKTIVA_ITEM_ID = 0;
    public static final int FLD_AKTIVA_ID = 1;
    public static final int FLD_RECEIVE_AKTIVA_ID = 2;
    public static final int FLD_QTY = 3;
    public static final int FLD_PRICE = 4;
    public static final int FLD_TOTAL_PRICE = 5;

    public static String[] fieldNames = {
        "RECEIVE_AKTIVA_ITEM_ID",
        "AKTIVA_ID",
        "RECEIVE_AKTIVA_ID",
        "QTY",
        "PRICE",
        "TOTAL_PRICE"
    };

    public static int[] fieldTypes = {
        TYPE_PK + TYPE_ID + TYPE_LONG,
        TYPE_LONG,
        TYPE_LONG,
        TYPE_INT,
        TYPE_FLOAT,
        TYPE_FLOAT

    };

    public PstReceiveAktivaItem() {
    }

    public PstReceiveAktivaItem(int i) throws DBException {
        super(new PstReceiveAktivaItem());
    }

    public PstReceiveAktivaItem(String sOid) throws DBException {
        super(new PstReceiveAktivaItem(0));
        if (!locate(sOid))
            throw new DBException(this, DBException.RECORD_NOT_FOUND);
        else
            return;
    }

    public PstReceiveAktivaItem(long lOid) throws DBException {
        super(new PstReceiveAktivaItem(0));
        String sOid = "0";
        try {
            sOid = String.valueOf(lOid);
        } catch (Exception e) {
            throw new DBException(this, DBException.RECORD_NOT_FOUND);
        }

        if (!locate(sOid))
            throw new DBException(this, DBException.RECORD_NOT_FOUND);
        else
            return;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public String getTableName() {
        return TBL_RECEIVE_AKTIVA_ITEM;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String getPersistentName() {
        return new PstReceiveAktivaItem().getClass().getName();
    }

    public long fetchExc(Entity ent) throws DBException {
        ReceiveAktivaItem aktiva = fetchExc(ent.getOID());
        ent = (Entity) aktiva;
        return aktiva.getOID();
    }

    public long insertExc(Entity ent) throws DBException {
        return insertExc((ReceiveAktiva) ent);
    }

    public long updateExc(Entity ent) throws DBException {
        return updateExc((ReceiveAktiva) ent);
    }

    public long deleteExc(Entity ent) throws DBException {
        if (ent == null) {
            throw  new DBException(this, DBException.RECORD_NOT_FOUND);
        }
        return deleteExc(ent.getOID());
    }

    public static ReceiveAktivaItem fetchExc(long Oid) throws DBException {
        try {
            ReceiveAktivaItem aktiva = new ReceiveAktivaItem();
            PstReceiveAktivaItem pstAktiva = new PstReceiveAktivaItem(Oid);
            aktiva.setOID(Oid);

            aktiva.setReceiveAktivaId(pstAktiva.getlong(FLD_AKTIVA_ID));
            aktiva.setQty(pstAktiva.getInt(FLD_QTY));
            aktiva.setPriceReceive(pstAktiva.getlong(FLD_PRICE));
            aktiva.setTotalPriceReceive(pstAktiva.getdouble(FLD_TOTAL_PRICE));

            return aktiva;
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstReceiveAktivaItem(0), DBException.UNKNOWN);
        }
    }

    public static long insertExc(ReceiveAktivaItem aktiva) throws DBException {
	return insertExc(aktiva, null);
    }

    public static long insertExc(ReceiveAktivaItem aktiva, Connection con) throws DBException {
        try {
            PstReceiveAktivaItem pstAktiva = new PstReceiveAktivaItem(0);

            pstAktiva.setLong(FLD_AKTIVA_ID, aktiva.getAktivaId());
            pstAktiva.setLong(FLD_RECEIVE_AKTIVA_ID, aktiva.getReceiveAktivaId());
            pstAktiva.setInt(FLD_QTY, aktiva.getQty());
            pstAktiva.setDouble(FLD_PRICE, aktiva.getPriceReceive());
            pstAktiva.setDouble(FLD_TOTAL_PRICE, aktiva.getTotalPriceReceive());
	    
	    if(con == null){
		pstAktiva.insert();
	    }else{
		pstAktiva.insertTran(con);
	    }
            aktiva.setOID(pstAktiva.getlong(FLD_RECEIVE_AKTIVA_ID));
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstReceiveAktivaItem(0), DBException.UNKNOWN);
        }
        return aktiva.getOID();
    }

    public static long updateExc(ReceiveAktivaItem aktiva) throws DBException {
	return updateExc(aktiva, null);
    }
    
    public static long updateExc(ReceiveAktivaItem aktiva, Connection con) throws DBException {
        try {
            if (aktiva != null && aktiva.getOID() != 0) {
                PstReceiveAktivaItem pstAktiva = new PstReceiveAktivaItem(aktiva.getOID());

                pstAktiva.setLong(FLD_AKTIVA_ID, aktiva.getAktivaId());
                pstAktiva.setLong(FLD_RECEIVE_AKTIVA_ID, aktiva.getReceiveAktivaId());
                pstAktiva.setInt(FLD_QTY, aktiva.getQty());
                pstAktiva.setDouble(FLD_PRICE, aktiva.getPriceReceive());
                pstAktiva.setDouble(FLD_TOTAL_PRICE, aktiva.getTotalPriceReceive());
		
		if(con == null){
		    pstAktiva.update();
		}else{
		    pstAktiva.updateTran(con);
		}
                return aktiva.getOID();
            }
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstReceiveAktivaItem(0), DBException.UNKNOWN);
        }
        return 0;
    }

    public static long deleteExc(long Oid) throws DBException {
	return deleteExc(Oid, null);
    }
    
    public static long deleteExc(long Oid, Connection con) throws DBException {
        try {
            PstReceiveAktivaItem pstAktiva = new PstReceiveAktivaItem(Oid);
	    if(con == null){
		pstAktiva.delete();
	    }else{
		pstAktiva.deleteTran(con);
	    }
        } catch (DBException dbe) {
            throw dbe;
        } catch (Exception e) {
            throw new DBException(new PstReceiveAktivaItem(0), DBException.UNKNOWN);
        }
        return Oid;
    }

    public static Vector list(int limitStart, int recordToGet, String whereClause, String order) {
        Vector lists = new Vector();
        DBResultSet dbrs = null;
        try {
            String sql = "SELECT * FROM " + TBL_RECEIVE_AKTIVA_ITEM + " ";
            if (whereClause != null && whereClause.length() > 0)
                sql = sql + " WHERE " + whereClause;

            if (order != null && order.length() > 0)
                sql = sql + " ORDER BY " + order;

            switch (DBHandler.DBSVR_TYPE) {
                case DBHandler.DBSVR_MYSQL:
                    if (limitStart == 0 && recordToGet == 0)
                        sql = sql + "";
                    else
                        sql = sql + " LIMIT " + limitStart + "," + recordToGet;
                    break;

                case DBHandler.DBSVR_POSTGRESQL:
                    if (limitStart == 0 && recordToGet == 0)
                        sql = sql + "";
                    else
                        sql = sql + " LIMIT " + recordToGet + " OFFSET " + limitStart;

                    break;

                case DBHandler.DBSVR_SYBASE:
                    break;

                case DBHandler.DBSVR_ORACLE:
                    break;

                case DBHandler.DBSVR_MSSQL:
                    break;

                default:
                    break;
            }

            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();

            while (rs.next()) {
                ReceiveAktivaItem aktiva = new ReceiveAktivaItem();
                resultToObject(rs, aktiva);
                lists.add(aktiva);
            }
        } catch (Exception error) {
            System.out.println(".:: " + new PstReceiveAktivaItem().getClass().getName() + ".list() : " + error.toString());
        } finally {
            DBResultSet.close(dbrs);
        }
        return lists;
    }

    private static void resultToObject(ResultSet rs, ReceiveAktivaItem aktiva) {
        try {
            aktiva.setOID(rs.getLong(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_RECEIVE_AKTIVA_ITEM_ID]));
            aktiva.setReceiveAktivaId(rs.getLong(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_RECEIVE_AKTIVA_ID]));
            aktiva.setAktivaId(rs.getLong(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_AKTIVA_ID]));
            aktiva.setQty(rs.getInt(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_QTY]));
            aktiva.setPriceReceive(rs.getDouble(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_PRICE]));
            aktiva.setTotalPriceReceive(rs.getDouble(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_TOTAL_PRICE]));

        } catch (Exception e) {
            System.out.println("resultToObject() " + e.toString());
        }
    }

    public static int getCount(String whereClause) {
        DBResultSet dbrs = null;
        try {
            String sql = "SELECT COUNT(" + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_RECEIVE_AKTIVA_ID] + ") " +
                    " FROM " + TBL_RECEIVE_AKTIVA_ITEM;
            if (whereClause != null && whereClause.length() > 0)
                sql = sql + " WHERE " + whereClause;

            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();

            int count = 0;
            while (rs.next()) {
                count = rs.getInt(1);
            }
            rs.close();
            return count;
        } catch (Exception e) {
            System.out.println(e);
            return 0;
        } finally {
            DBResultSet.close(dbrs);
        }
    }


    /** gadnyana
     * mencari list item berdasarkan oid main (order aktiva)
     * @param oidReceiveAktiva
     * @return
     */
    public static Vector getListItem(long oidReceiveAktiva) {
        Vector lists = new Vector();
        DBResultSet dbrs = null;
        try {
            String sql = "SELECT " +
                    " IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_RECEIVE_AKTIVA_ITEM_ID] +
                    " ,IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_QTY] +
                    " ,IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_PRICE] +
                    " ,IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_TOTAL_PRICE] +
                    " ,IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_AKTIVA_ID] +
                    " ,MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_KODE] +
                    " ,MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_NAME] +
                    " ,MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_ID_PERKIRAAN_AKTIVA] +
                    " FROM " + TBL_RECEIVE_AKTIVA_ITEM + " AS IT " +
                    " INNER JOIN " + PstReceiveAktiva.TBL_RECEIVE_AKTIVA + " AS OD " +
                    " ON IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_RECEIVE_AKTIVA_ID] +
                    " = OD." + PstReceiveAktiva.fieldNames[PstReceiveAktiva.FLD_RECEIVE_AKTIVA_ID] +
                    " INNER JOIN " + PstModulAktiva.TBL_AKTIVA + " AS MA " +
                    " ON IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_AKTIVA_ID] +
                    " = MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_AKTIVA_ID] +
                    " WHERE OD." + PstReceiveAktiva.fieldNames[PstReceiveAktiva.FLD_RECEIVE_AKTIVA_ID] + "=" + oidReceiveAktiva +
                    " ORDER BY MA." + PstModulAktiva.fieldNames[PstModulAktiva.FLD_KODE];
            System.out.println(sql);
            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();

            while (rs.next()) {
                ReceiveAktivaItem orderAktivaItem = new ReceiveAktivaItem();
                ModulAktiva modulAktiva = new ModulAktiva();
                Vector vect = new Vector();

                orderAktivaItem.setOID(rs.getLong(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_RECEIVE_AKTIVA_ITEM_ID]));
                orderAktivaItem.setQty(rs.getInt(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_QTY]));
                orderAktivaItem.setPriceReceive(rs.getDouble(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_PRICE]));
                orderAktivaItem.setTotalPriceReceive(rs.getDouble(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_TOTAL_PRICE]));
                orderAktivaItem.setAktivaId(rs.getLong(PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_AKTIVA_ID]));
                vect.add(orderAktivaItem);

                modulAktiva.setKode(rs.getString(PstModulAktiva.fieldNames[PstModulAktiva.FLD_KODE]));
                modulAktiva.setName(rs.getString(PstModulAktiva.fieldNames[PstModulAktiva.FLD_NAME]));
                modulAktiva.setIdPerkiraanAktiva(rs.getLong(PstModulAktiva.fieldNames[PstModulAktiva.FLD_ID_PERKIRAAN_AKTIVA]));
                vect.add(modulAktiva);

                lists.add(vect);
            }
        } catch (Exception error) {
            System.out.println(".:: " + new PstReceiveAktivaItem().getClass().getName() + ".list() : " + error.toString());
        } finally {
            DBResultSet.close(dbrs);
        }
        return lists;
    }


    /** gadnyana
     * untuk mencvari total order berdasarkan oid order
     * @return
     */
    public static double getTotalReceiveAktivaItem(long oidReceiveAktiva) {
        DBResultSet dbrs = null;
        double total = 0.0;
        try {
            String sql = "SELECT " +
                    " SUM(IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_TOTAL_PRICE] + ")" +
                    " FROM " + TBL_RECEIVE_AKTIVA_ITEM + " AS IT " +
                    " WHERE IT." + PstReceiveAktivaItem.fieldNames[PstReceiveAktivaItem.FLD_RECEIVE_AKTIVA_ID] + "=" + oidReceiveAktiva;
            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            while (rs.next()) {
                total = rs.getDouble(1);
            }
        } catch (Exception error) {
            System.out.println(".:: " + new PstReceiveAktivaItem().getClass().getName() + ".list() : " + error.toString());
        } finally {
            DBResultSet.close(dbrs);
        }
        return total;
    }
    
     public static long getRecAktivaIdByAktivaId(long lAktivaId){
        DBResultSet dbrs = null;
        long lResult = 0;
        try{
            String sql = "SELECT "+fieldNames[FLD_RECEIVE_AKTIVA_ID]+" FROM "+TBL_RECEIVE_AKTIVA_ITEM+
                         " WHERE "+fieldNames[FLD_AKTIVA_ID]+" = "+lAktivaId;           
            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            while(rs.next()){
                lResult = rs.getLong(fieldNames[FLD_RECEIVE_AKTIVA_ID]);
            }
        }catch(Exception e){}
        return lResult;
    }
     
     public static long getRecAktivaItemIdByAktivaId(long lAktivaId){
        DBResultSet dbrs = null;
        long lResult = 0;
        try{
            String sql = "SELECT "+fieldNames[FLD_RECEIVE_AKTIVA_ITEM_ID]+" FROM "+TBL_RECEIVE_AKTIVA_ITEM+
                         " WHERE "+fieldNames[FLD_AKTIVA_ID]+" = "+lAktivaId;
            
            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            while(rs.next()){
                lResult = rs.getLong(fieldNames[FLD_RECEIVE_AKTIVA_ITEM_ID]);
            }
        }catch(Exception e){}
        return lResult;
    } 
     
     public static long insertRecAktivaItem(long lRecAktivaId, long lAktivaId, int iQty){
	    return insertRecAktivaItem(lRecAktivaId, lAktivaId, iQty, null);
     }
	 
     public static long insertRecAktivaItem(long lRecAktivaId, long lAktivaId, int iQty, Connection con){
        long lResult = 0;
        int jumlahAktiva = 0;
        if(iQty > 0){
            jumlahAktiva = iQty;
        }else{
            jumlahAktiva = 1;
        }
        
        ReceiveAktivaItem objRecAktivaItem = new ReceiveAktivaItem();
        ModulAktiva objModAktiva = new ModulAktiva();
        if(lAktivaId != 0){
            try{
                objModAktiva = PstModulAktiva.fetchExc(lAktivaId);
            }catch(Exception e){}
        }
        try{
            objRecAktivaItem.setPriceReceive(objModAktiva.getHargaPerolehan() / jumlahAktiva);
            objRecAktivaItem.setQty(jumlahAktiva);
            objRecAktivaItem.setReceiveAktivaId(lRecAktivaId);
            objRecAktivaItem.setTotalPriceReceive(objModAktiva.getHargaPerolehan());
            objRecAktivaItem.setAktivaId(lAktivaId);
	    if(con == null){
		lResult = insertExc(objRecAktivaItem);
	    }else{
		lResult = insertExc(objRecAktivaItem, con);
	    }
        }catch(Exception e){}
        return lResult;
     }
     
     public static long updateRecAktivaItem(long lRecAktivaId, long lAktivaId, int iQty, Connection con){
        long lResult = 0;
        long lRecAktItemId = 0;
        ReceiveAktivaItem objRecAktivaItem = new ReceiveAktivaItem();
        ModulAktiva objModAktiva = new ModulAktiva();
	int jumlahAktiva = 0;
        if(iQty > 0){
            jumlahAktiva = iQty;
        }else{
            jumlahAktiva = 1;
        }
	
        if(lAktivaId != 0){
            try{
                objModAktiva = PstModulAktiva.fetchExc(lAktivaId);
            }catch(Exception e){}
        }
        try{
            lRecAktItemId = getRecAktivaItemIdByAktivaId(lAktivaId);
            if(lRecAktItemId != 0){
                objRecAktivaItem = fetchExc(lRecAktItemId);
            }
            if(objRecAktivaItem != null){
                objRecAktivaItem.setPriceReceive(objModAktiva.getHargaPerolehan() / jumlahAktiva);
                objRecAktivaItem.setQty(iQty);
                objRecAktivaItem.setReceiveAktivaId(lRecAktivaId);
                objRecAktivaItem.setTotalPriceReceive(objModAktiva.getHargaPerolehan());
                objRecAktivaItem.setAktivaId(lAktivaId);
                lResult = PstReceiveAktivaItem.updateExc(objRecAktivaItem, con);
            }
        }catch(Exception e){}
        return lResult = 0;
     }
     
     public static long deleteRecAktivaItem(long lAktivaId){
	return deleteRecAktivaItem(lAktivaId, null);
     }
     public static long deleteRecAktivaItem(long lAktivaId, Connection con){
        long lResult = 0;
        long lRecAktivaItemId = 0;
        if(lAktivaId != 0){
            try{
                lRecAktivaItemId = getRecAktivaItemIdByAktivaId(lAktivaId);
            }catch(Exception e){}
        }
        if(lRecAktivaItemId != 0){
            try{
		if(con == null){
		    lResult = deleteExc(lRecAktivaItemId);
		}else{
		    lResult = deleteExc(lRecAktivaItemId, con);
		}
            }catch(Exception e){}
        }
        return lResult;
     }
}
