/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dimata.posbo.ajax;

import com.dimata.gui.jsp.ControlCombo;
import com.dimata.pos.form.billing.FrmBillMain;
import com.dimata.posbo.entity.masterdata.PstTableRoom;
import com.dimata.posbo.entity.masterdata.TableRoom;
import com.dimata.qdep.form.FRMQueryString;
import java.util.Vector;
import javax.servlet.http.HttpServlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
/**
 *
 * @author dimata005
 */
public class CheckTableFromRoom extends HttpServlet{
     /* Generated by Together */
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
    }

    /** Destroys the servlet.
     */
    public void destroy() {

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, java.io.IOException {
        processRequest(request, response);
    }

    /** Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     */
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, java.io.IOException {
        processRequest(request, response);
    }

    /** Returns a short description of the servlet.
     */
    public String getServletInfo() {
        return "Short description";
    }

    private void processRequest(HttpServletRequest request, HttpServletResponse response) {
        try{
            //String buffer="false";
            /**
             * create fungsi check contract price with oidsupplier and oidmaterial
             */
            long roomId = FRMQueryString.requestLong(request,"roomId");
            long tableId = FRMQueryString.requestLong(request,"tableId");
            
            //create fungsi cek Nilai Konversi
            //double resultKonversi = 0.0;
            String comboBox="";
            Vector val_locationid = new Vector(1,1);
            Vector key_locationid = new Vector(1,1);
            
            try{
                
                String whereRoom = PstTableRoom.fieldNames[PstTableRoom.FLD_ROOM_ID]+"='"+roomId+"'";
                
                if(tableId!=0){
                    whereRoom=whereRoom+" AND "+ PstTableRoom.fieldNames[PstTableRoom.FLD_TABLE_ID]+"='"+tableId+"'";
                }
                
                Vector vt_loc = PstTableRoom.list(0,0,whereRoom, PstTableRoom.fieldNames[PstTableRoom.FLD_TABLE_NUMBER]);
                for(int d=0;d<vt_loc.size();d++){
                        TableRoom tableRoom = (TableRoom)vt_loc.get(d);
                        val_locationid.add(""+tableRoom.getOID()+"");
                        key_locationid.add(tableRoom.getTableNumber());
                }
                
                comboBox=ControlCombo.drawBoostrap(FrmBillMain.fieldNames[FrmBillMain.FRM_FIELD_TABLE_ID],"form-control", null, "",val_locationid,key_locationid, "");
                   
            }catch(Exception ex){
                comboBox="";
            }
           
            
            response.getWriter().println(comboBox);

         }catch(Exception ex){
            ex.printStackTrace();
         }
    }
}
