/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dimata.posbo.ajax;

/**
 *
 * @author dimata005
 */

import com.dimata.common.entity.location.PstLocation;
import com.dimata.gui.jsp.ControlCombo;
import com.dimata.pos.entity.billing.PstBillMain;
import com.dimata.pos.form.billing.FrmBillMain;
import com.dimata.posbo.entity.masterdata.PstRoom;
import com.dimata.posbo.entity.masterdata.PstTableRoom;
import com.dimata.posbo.entity.masterdata.TableRoom;
import com.dimata.qdep.form.FRMQueryString;
import java.util.Vector;
import javax.servlet.http.HttpServlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
/**
 *
 * @author dimata005
 */
public class CreateTableFromRoom extends HttpServlet{
     /* Generated by Together */
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
    }

    /** Destroys the servlet.
     */
    public void destroy() {

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, java.io.IOException {
        processRequest(request, response);
    }

    /** Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     */
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, java.io.IOException {
        processRequest(request, response);
    }

    /** Returns a short description of the servlet.
     */
    public String getServletInfo() {
        return "Short description";
    }

    private void processRequest(HttpServletRequest request, HttpServletResponse response) {
        try{
            //String buffer="false";
            /**
             * create fungsi check contract price with oidsupplier and oidmaterial
             */
            long roomId = FRMQueryString.requestLong(request,"roomId");
            int capacity = FRMQueryString.requestInt(request,"capacity");
            long locationId= FRMQueryString.requestLong(request,"locationId");
            
            //create fungsi cek Nilai Konversi
            //double resultKonversi = 0.0;
            String comboBox="";
//            Vector val_locationid = new Vector(1,1);
//            Vector key_locationid = new Vector(1,1);
            String whereRoom = "";
            
//             String whereRoomx = PstLocation.fieldNames[PstLocation.FLD_LOCATION_ID]+"='"+locationId+"'";   
//             Vector vt_loc = PstRoom.list(0,0,whereRoom, PstLocation.fieldNames[PstLocation.FLD_CODE]);
//             for(int d=0;d<vt_loc.size();d++){
//                    Room room = (Room)vt_loc.get(d);
//             }
            
            try{
                
                whereRoom=PstTableRoom.fieldNames[PstTableRoom.FLD_LOCATION_ID]+"='"+locationId+"'";
                
                if(roomId!=0){
                        whereRoom = whereRoom + " AND "+PstTableRoom.fieldNames[PstTableRoom.FLD_ROOM_ID]+"='"+roomId+"'";
                }
                
                Vector vt_loc = PstTableRoom.list(0,0,whereRoom, PstTableRoom.fieldNames[PstTableRoom.FLD_TABLE_NUMBER]);
                
                for(int d=0;d<vt_loc.size();d++){
                    
                       TableRoom tableRoom = (TableRoom)vt_loc.get(d);
                       
                       //disini pengecekan apakah ada bill atau tidak
                       String whereTable=PstTableRoom.fieldNames[PstTableRoom.FLD_TABLE_ID]+"='"+tableRoom.getOID()+"'";
                       int totalPaxFromTable = PstBillMain.getSumPaxOpenBillFromTable(whereTable);
                       
                       String whereTableBill=PstBillMain.fieldNames[PstBillMain.FLD_TABLE_ID]+"='"+tableRoom.getOID()+"'";
                       int totalOpenBill = PstBillMain.getCountOpenBillFromTable(whereTableBill);
                       int sisaPax = tableRoom.getCapacity()-totalPaxFromTable;
                       
                       if(capacity==0 || sisaPax>=capacity){
                           comboBox=comboBox + "<div class=\"items\">";
                           comboBox=comboBox + "<strong>"+tableRoom.getTableNumber()+"</strong><br />";

                               if(tableRoom.getStatus()==0){//free
                                   comboBox=comboBox + "<a href=\"addorder.jsp?FRM_FIELD_ROOM_ID="+tableRoom.getRoomId()+"&FRM_FIELD_TABLE_ID="+tableRoom.getOID()+"&PAX_BALANCE="+sisaPax+"\"><img src=\"../styles/takingorder/img/green.png\" alt=\"Smiley face\" width=\"40\"></a><br>";
                               }else if(tableRoom.getStatus()==1){//half
                                   comboBox=comboBox + "<a href=\"addorder.jsp?FRM_FIELD_ROOM_ID="+tableRoom.getRoomId()+"&FRM_FIELD_TABLE_ID="+tableRoom.getOID()+"&PAX_BALANCE="+sisaPax+"\"><img src=\"../styles/takingorder/img/yellow.png\" alt=\"Smiley face\" width=\"40\"></a><br>";
                               }else{//full
                                   comboBox=comboBox + "<a href=\"addorder.jsp?FRM_FIELD_ROOM_ID="+tableRoom.getRoomId()+"&FRM_FIELD_TABLE_ID="+tableRoom.getOID()+"&PAX_BALANCE="+sisaPax+"\"><img src=\"../styles/takingorder/img/red.png\" alt=\"Smiley face\" width=\"40\"></a><br>";
                               }

                               comboBox=comboBox + "Capacity : <strong>"+sisaPax+"</strong><br />";
                               if(tableRoom.getStatusTable()==0){
                                    comboBox=comboBox + "Status : <strong>Clean</strong><a href=\"tableorder.jsp?FRM_FIELD_ROOM_ID="+tableRoom.getRoomId()+"&FRM_FIELD_TABLE_ID="+tableRoom.getOID()+"&updateTable=1&updateStatusMeja=1\">Update</a><br />";
                               }else{
                                    comboBox=comboBox + "Status: <strong>Dirty </strong><a href=\"tableorder.jsp?FRM_FIELD_ROOM_ID="+tableRoom.getRoomId()+"&FRM_FIELD_TABLE_ID="+tableRoom.getOID()+"&updateTable=1&updateStatusMeja=0\">Update</a><br />";
                               }

                           //jika bill cuma 1 langsung aja masuk ke bill
                           comboBox=comboBox + "Bill <strong>: <a href=\"salesmobile.jsp?FRM_FIELD_ROOM_ID="+tableRoom.getRoomId()+"&FRM_FIELD_TABLE_ID="+tableRoom.getOID()+"\">"+totalOpenBill+"</a></strong><br />";

                           comboBox=comboBox +"</div>";
                       }
                       
                }

            }catch(Exception ex){
                comboBox="";
            }
            
            response.getWriter().println(comboBox);

         }catch(Exception ex){
            ex.printStackTrace();
         }
    }
}
