/* Generated by Together */



package com.dimata.interfaces.common.loginsystem;



public interface I_LoginSession {



    public static String CLASS_NAME = "com.dimata.jkjonline.session.ppk.SessPpkSession";



    public int doLogin(String loginID, String password);



}

