/* Generated by Together */

package com.dimata.aiso.form.search;

import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;
import com.dimata.aiso.entity.search.SrcReceiveAktiva;

import javax.servlet.http.HttpServletRequest;

public class FrmSrcReceiveAktiva extends FRMHandler implements I_FRMInterface, I_FRMType {

    public static final String FRM_SEARCH_RECEIVE_AKTIVA = "FRM_SEARCH_RECEIVE_AKTIVA";
    public static final int FRM_SEARCH_NOMOR_RECEIVE = 0;
    public static final int FRM_SEARCH_NAMA_SUPPLIER = 1;
    public static final int FRM_SEARCH_TYPE = 2;
    public static final int FRM_SEARCH_TANGGAL_AWAL = 3;
    public static final int FRM_SEARCH_TANGGAL_AKHIR = 4;

    public static String[] fieldNames = {
        "FRM_SEARCH_NOMOR_RECEIVE",
        "FRM_SEARCH_CONTACT_NAME",
        "FRM_SEARCH_ORDER_TYPE",
        "FRM_SEARCH_FROM_DATE",
        "FRM_SEARCH_UNTIL_DATE"
    };

    public static int[] fieldTypes = {
        TYPE_STRING,
        TYPE_STRING,
        TYPE_INT,
        TYPE_DATE,
        TYPE_DATE
    };

    private SrcReceiveAktiva srcReceiveAktiva = new SrcReceiveAktiva();

    public FrmSrcReceiveAktiva() {
    }

    public FrmSrcReceiveAktiva(HttpServletRequest request) {
        super(new FrmSrcReceiveAktiva(), request);
    }

    public String getFormName() {
        return this.FRM_SEARCH_RECEIVE_AKTIVA;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public SrcReceiveAktiva getEntityObject() {
        return srcReceiveAktiva;
    }

    public void requestEntityObject(SrcReceiveAktiva srcReceiveAktiva) {
        try {
            this.requestParam();

            srcReceiveAktiva.setNomorReceive(getString(FRM_SEARCH_NOMOR_RECEIVE));
            srcReceiveAktiva.setNameSupplier(getString(FRM_SEARCH_NAMA_SUPPLIER));
            srcReceiveAktiva.setType(getInt(FRM_SEARCH_TYPE));
            srcReceiveAktiva.setTanggalAwal(getDate(FRM_SEARCH_TANGGAL_AWAL));
            srcReceiveAktiva.setTanggalakhir(getDate(FRM_SEARCH_TANGGAL_AKHIR));

            this.srcReceiveAktiva = srcReceiveAktiva;
        } catch (Exception e) {
            System.out.println("EXC...");
            srcReceiveAktiva = new SrcReceiveAktiva();
        }
    }
}
