/* Generated by Together */

package com.dimata.aiso.form.aktiva;

import com.dimata.aiso.entity.aktiva.OrderAktiva;
import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;

import javax.servlet.http.HttpServletRequest;

public class FrmOrderAktiva extends FRMHandler implements I_FRMInterface, I_FRMType {
    public static final String FRM_ORDER_AKTIVA = "FRM_ORDER_AKTIVA";
    public static final int FRM_NOMOR_ORDER = 0;
    public static final int FRM_TANGGAL_ORDER = 1;
    public static final int FRM_SUPPLIER_ID = 2;
    public static final int FRM_TYPE_PEMBAYARAN = 3;
    public static final int FRM_ID_PERKIRAAN_PAYMENT = 4;
    public static final int FRM_ID_PERKIRAAN_DP = 5;
    public static final int FRM_ID_CURRENCY = 6;
    public static final int FRM_VALUE_RATE = 7;
    public static final int FRM_DOWN_PAYMENT = 8;
    public static final int FRM_ORDER_STATUS = 9;

    public static String[] fieldNames =
            {
                "FRM_NOMOR_ORDER",
                "FRM_TANGGAL_ORDER",
                "FRM_SUPPLIER_ID",
                "FRM_TYPE_PEMBAYARAN",
                "FRM_ID_PERKIRAAN_PAYMENT",
                "FRM_ID_PERKIRAAN_DP",
                "FRM_ID_CURRENCY",
                "FRM_VALUE_RATE",
                "FRM_DOWN_PAYMENT",
                "FRM_ORDER_STATUS"
            };

    public static int[] fieldTypes =
            {
                TYPE_STRING,
                TYPE_DATE,
                TYPE_LONG,
                TYPE_INT,
                TYPE_LONG,
                TYPE_LONG,
                TYPE_LONG,
                TYPE_FLOAT,
                TYPE_FLOAT,
                TYPE_INT
            };

    private OrderAktiva aktiva;

    public FrmOrderAktiva(OrderAktiva aktiva) {
        this.aktiva = aktiva;
    }

    public FrmOrderAktiva(HttpServletRequest request, OrderAktiva aktiva) {
        super(new FrmOrderAktiva(aktiva), request);
        this.aktiva = aktiva;
    }

    public String getFormName() {
        return FRM_ORDER_AKTIVA;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public OrderAktiva getEntityObject() {
        return aktiva;
    }

    public void requestEntityObject(OrderAktiva aktiva) {
        try {
            this.requestParam();
            aktiva.setNomorOrder(this.getString(FRM_NOMOR_ORDER));
            aktiva.setTanggalOrder(this.getDate(FRM_TANGGAL_ORDER));
            aktiva.setSupplierId(this.getLong(FRM_SUPPLIER_ID));
            aktiva.setTypePembayaran(this.getInt(FRM_TYPE_PEMBAYARAN));
            aktiva.setIdPerkiraanPayment(this.getLong(FRM_ID_PERKIRAAN_PAYMENT));
            aktiva.setIdPerkiraanDp(this.getLong(FRM_ID_PERKIRAAN_DP));
            aktiva.setIdCurrency(this.getLong(FRM_ID_CURRENCY));
            aktiva.setValueRate(this.getDouble(FRM_VALUE_RATE));
            aktiva.setDownPayment(this.getDouble(FRM_DOWN_PAYMENT));
            aktiva.setOrderStatus(this.getInt(FRM_ORDER_STATUS));

            this.aktiva = aktiva;
        } catch (Exception e) {
            aktiva = new OrderAktiva();
        }
    }
}
