/* Generated by Together */

package com.dimata.aiso.form.aktiva;

import com.dimata.aiso.entity.aktiva.PenyusutanAktiva;
import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;

import javax.servlet.http.HttpServletRequest;

public class FrmPenyusutanAktiva extends FRMHandler implements I_FRMInterface, I_FRMType {
    public static final String FRM_PENYUSUTAN_AKTIVA = "FRM_PENYUSUTAN_AKTIVA";
    public static final int FRM_AKTIVA_ID = 0;
    public static final int FRM_PERIODE_ID = 1;
    public static final int FRM_VALUE_PNY = 2;

    public static String[] fieldNames = {
        "FRM_AKTIVA_ID",
        "FRM_PERIODE_ID",
        "FRM_VALUE_PNY"
    };

    public static int[] fieldTypes =
            {
                TYPE_LONG,
                TYPE_LONG,
                TYPE_FLOAT
            };

    private PenyusutanAktiva aktiva;

    public FrmPenyusutanAktiva(PenyusutanAktiva aktiva) {
        this.aktiva = aktiva;
    }

    public FrmPenyusutanAktiva(HttpServletRequest request, PenyusutanAktiva aktiva) {
        super(new FrmPenyusutanAktiva(aktiva), request);
        this.aktiva = aktiva;
    }

    public String getFormName() {
        return FRM_PENYUSUTAN_AKTIVA;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public PenyusutanAktiva getEntityObject() {
        return aktiva;
    }

    public void requestEntityObject(PenyusutanAktiva aktiva) {
        try {
            this.requestParam();
            aktiva.setAktivaId(this.getLong(FRM_AKTIVA_ID));
            aktiva.setPeriodeId(this.getLong(FRM_PERIODE_ID));
            aktiva.setValue_pny(this.getDouble(FRM_VALUE_PNY));

            this.aktiva = aktiva;
        } catch (Exception e) {
            aktiva = new PenyusutanAktiva();
        }
    }
}
