/* Generated by Together */

package com.dimata.aiso.form.aktiva;

import com.dimata.aiso.entity.aktiva.ReceiveAktiva;
import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;

import javax.servlet.http.HttpServletRequest;

public class FrmReceiveAktiva extends FRMHandler implements I_FRMInterface, I_FRMType {
    public static final String FRM_RECEIVE_AKTIVA = "FRM_RECEIVE_AKTIVA";
    public static final int FRM_NOMOR_RECEIVE = 0;
    public static final int FRM_TANGGAL_RECEIVE = 1;
    public static final int FRM_SUPPLIER_ID = 2;
    public static final int FRM_TYPE_PEMBAYARAN = 3;
    public static final int FRM_ID_PERKIRAAN_PAYMENT = 4;
    public static final int FRM_ID_PERKIRAAN_DP = 5;
    public static final int FRM_ID_CURRENCY = 6;
    public static final int FRM_VALUE_RATE = 7;
    public static final int FRM_DOWN_PAYMENT = 8;
    public static final int FRM_ORDER_AKTIVA_ID = 9;
    public static final int FRM_NOMOR_INVOICE = 10;
    public static final int FRM_RECEIVE_STATUS = 11;

    public static String[] fieldNames = {
        "FRM_NOMOR_RECEIVE",
        "FRM_TANGGAL_RECEIVE",
        "FRM_SUPPLIER_ID",
        "FRM_TYPE_PEMBAYARAN",
        "FRM_ID_PERKIRAAN_PAYMENT",
        "FRM_ID_PERKIRAAN_DP",
        "FRM_ID_CURRENCY",
        "FRM_VALUE_RATE",
        "FRM_DOWN_PAYMENT",
        "FRM_ORDER_AKTIVA_ID",
        "FRM_NOMOR_INVOICE",
        "FRM_RECEIVE_STATUS"
    };

    public static int[] fieldTypes =
            {
                TYPE_STRING,
                TYPE_DATE,
                TYPE_LONG,
                TYPE_INT,
                TYPE_LONG,
                TYPE_LONG,
                TYPE_LONG,
                TYPE_FLOAT,
                TYPE_FLOAT,
                TYPE_LONG,
                TYPE_STRING,
                TYPE_INT
            };

    private ReceiveAktiva aktiva;

    public FrmReceiveAktiva(ReceiveAktiva aktiva) {
        this.aktiva = aktiva;
    }

    public FrmReceiveAktiva(HttpServletRequest request, ReceiveAktiva aktiva) {
        super(new FrmReceiveAktiva(aktiva), request);
        this.aktiva = aktiva;
    }

    public String getFormName() {
        return FRM_RECEIVE_AKTIVA;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public ReceiveAktiva getEntityObject() {
        return aktiva;
    }

    public void requestEntityObject(ReceiveAktiva aktiva) {
        try {
            this.requestParam();
            aktiva.setNomorReceive(this.getString(FRM_NOMOR_RECEIVE));
            aktiva.setTanggalReceive(this.getDate(FRM_TANGGAL_RECEIVE));
            aktiva.setSupplierId(this.getLong(FRM_SUPPLIER_ID));
            aktiva.setTypePembayaran(this.getInt(FRM_TYPE_PEMBAYARAN));
            aktiva.setIdPerkiraanPayment(this.getLong(FRM_ID_PERKIRAAN_PAYMENT));
            aktiva.setIdPerkiraanDp(this.getLong(FRM_ID_PERKIRAAN_DP));
            aktiva.setIdCurrency(this.getLong(FRM_ID_CURRENCY));
            aktiva.setValueRate(this.getDouble(FRM_VALUE_RATE));
            aktiva.setDownPayment(this.getDouble(FRM_DOWN_PAYMENT));
            aktiva.setOrderAktivaId(this.getLong(FRM_ORDER_AKTIVA_ID));
            aktiva.setNomorInvoice(this.getString(FRM_NOMOR_INVOICE));
            aktiva.setReceiveStatus(this.getInt(FRM_RECEIVE_STATUS));

            this.aktiva = aktiva;
        } catch (Exception e) {
            aktiva = new ReceiveAktiva();
        }
    }
}
