/* Generated by Together */

package com.dimata.aiso.form.aktiva;

import com.dimata.aiso.entity.aktiva.ReceiveAktivaItem;
import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;

import javax.servlet.http.HttpServletRequest;

public class FrmReceiveAktivaItem extends FRMHandler implements I_FRMInterface, I_FRMType {
    public static final String FRM_RECEIVE_AKTIVA_ITEM = "FRM_RECEIVE_AKTIVA_ITEM";
    public static final int FRM_AKTIVA_ID = 0;
    public static final int FRM_RECEIVE_AKTIVA_ID = 1;
    public static final int FRM_QTY = 2;
    public static final int FRM_PRICE = 3;
    public static final int FRM_TOTAL_PRICE = 4;

    public static String[] fieldNames =
            {
                "FRM_AKTIVA_ID",
                "FRM_RECEIVE_AKTIVA_ID",
                "FRM_QTY",
                "FRM_PRICE",
                "FRM_TOTAL_PRICE"
            };

    public static int[] fieldTypes =
            {
                TYPE_LONG,
                TYPE_LONG,
                TYPE_INT,
                TYPE_FLOAT,
                TYPE_FLOAT
            };

    private ReceiveAktivaItem aktiva;

    public FrmReceiveAktivaItem(ReceiveAktivaItem aktiva) {
        this.aktiva = aktiva;
    }

    public FrmReceiveAktivaItem(HttpServletRequest request, ReceiveAktivaItem aktiva) {
        super(new FrmReceiveAktivaItem(aktiva), request);
        this.aktiva = aktiva;
    }

    public String getFormName() {
        return FRM_RECEIVE_AKTIVA_ITEM;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }

    public int getFieldSize() {
        return fieldNames.length;
    }

    public ReceiveAktivaItem getEntityObject() {
        return aktiva;
    }

    public void requestEntityObject(ReceiveAktivaItem aktiva) {
        try {
            this.requestParam();
            aktiva.setAktivaId(this.getLong(FRM_AKTIVA_ID));
            aktiva.setReceiveAktivaId(this.getLong(FRM_RECEIVE_AKTIVA_ID));
            aktiva.setQty(this.getInt(FRM_QTY));
            aktiva.setPriceReceive(this.getDouble(FRM_PRICE));
            aktiva.setTotalPriceReceive(this.getDouble(FRM_TOTAL_PRICE));

            this.aktiva = aktiva;
        } catch (Exception e) {
            aktiva = new ReceiveAktivaItem();
        }
    }
}
