/* Generated by Together */

package com.dimata.pos.DsjCashierInterface;
import java.util.*;
public interface I_DsjCashierMain { 
    //component visibility
    public static final int DISABLED=0;
    public static final int ENABLED=1;
        
    //type entry for sales
    public static final int OPTIONAL=0;
    public static final int REQUIRED=1;
    
    public Vector getProduct(String code);
    public Vector getEmployee(String loginName,String password,int tipe);
    public Vector getCurrency();
    public Vector searchingByName(String key); 
    public Vector searchingByCode(String key);
    public Vector getObjShift();
    public Vector getObjSales();
    public Vector getObjUnit();
    public Vector getMaster(long cashMasterId);
}
