/* Generated by Together */

package com.dimata.pos.entity.payment;

import com.dimata.qdep.entity.Entity;
import java.util.Date;

public class CashPayments extends Entity {
    
    private long billMainId;
    private int paymentType;
    private long creditCardId=0;
    private long currencyId;
    private double rate;
    private double amount;
    private Date payDateTime = new Date();
    private int updateStatus=0;
    private int paymentStatus;
    public CashPayments() {
    }
    
    public long getBillMainId(){
        return billMainId;}
    public void setBillMainId(long billMainId){
        this.billMainId=billMainId;}
    
    public int getPaymentType(){
        return paymentType;}
    public void setPaymentType(int paymentType){
        this.paymentType=paymentType;}
    
    
    public long getCurrencyId(){
        return currencyId;}
    public void setCurrencyId(long currencyId){
        this.currencyId=currencyId;}
    
    public double getRate(){
        return rate;}
    public void setRate(double rate){
        this.rate=rate;}
    
    public double getAmount(){
        return amount;}
    public void setAmount(double amount){
        this.amount=amount;}
    
    /**
     * Getter for property payDateTime.
     * @return Value of property payDateTime.
     */
    public Date getPayDateTime() {
        return payDateTime;
    }
    
    /**
     * Setter for property payDateTime.
     * @param payDateTime New value of property payDateTime.
     */
    public void setPayDateTime(Date payDateTime) {
        this.payDateTime = payDateTime;
    }
    
    /**
     * Getter for property updateStatus.
     * @return Value of property updateStatus.
     */
    public int getUpdateStatus() {
        return updateStatus;
    }
    
    /**
     * Setter for property updateStatus.
     * @param updateStatus New value of property updateStatus.
     */
    public void setUpdateStatus(int updateStatus) {
        this.updateStatus = updateStatus;
    }
    
    /**
     * Getter for property paymentStatus.
     * @return Value of property paymentStatus.
     */
    public int getPaymentStatus() {
        return paymentStatus;
    }
    
    /**
     * Setter for property paymentStatus.
     * @param paymentStatus New value of property paymentStatus.
     */
    public void setPaymentStatus(int paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    
}

