/* Generated by Together */

package com.dimata.pos.entity.payment;

import com.dimata.qdep.entity.Entity;
import java.util.Date;

public class CashPayments1 extends Entity {
    
    private long billMainId;
    private long paymentType;
    private long creditCardId=0;
    private long currencyId;
    private double rate;
    private double amount;
    private Date payDateTime = new Date();
    private int updateStatus=0;
    private int paymentStatus;

    //untuk return payment
    private double amountReturn;
    private long cashCashierId = 0;
    
    private int typeSistemPayment=0;
    
    public CashPayments1() {
    }
    
    public long getBillMainId(){
        return billMainId;}
    public void setBillMainId(long billMainId){
        this.billMainId=billMainId;}
    
    public long getPaymentType(){
        return paymentType;}
    
    public void setPaymentType(long paymentType){
        this.paymentType=paymentType;}
    
    
    public long getCurrencyId(){
        return currencyId;}
    public void setCurrencyId(long currencyId){
        this.currencyId=currencyId;}
    
    public double getRate(){
        return rate;}
    public void setRate(double rate){
        this.rate=rate;}
    
    public double getAmount(){
        return amount;}
    public void setAmount(double amount){
        this.amount=amount;}
    
    /**
     * Getter for property payDateTime.
     * @return Value of property payDateTime.
     */
    public Date getPayDateTime() {
        return payDateTime;
    }
    
    /**
     * Setter for property payDateTime.
     * @param payDateTime New value of property payDateTime.
     */
    public void setPayDateTime(Date payDateTime) {
        this.payDateTime = payDateTime;
    }
    
    /**
     * Getter for property updateStatus.
     * @return Value of property updateStatus.
     */
    public int getUpdateStatus() {
        return updateStatus;
    }
    
    /**
     * Setter for property updateStatus.
     * @param updateStatus New value of property updateStatus.
     */
    public void setUpdateStatus(int updateStatus) {
        this.updateStatus = updateStatus;
    }
    
    /**
     * Getter for property paymentStatus.
     * @return Value of property paymentStatus.
     */
    public int getPaymentStatus() {
        return paymentStatus;
    }
    
    /**
     * Setter for property paymentStatus.
     * @param paymentStatus New value of property paymentStatus.
     */
    public void setPaymentStatus(int paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    
    /**
     * @return the amountReturn
     */
    public double getAmountReturn() {
        return amountReturn;
}

    /**
     * @param amountReturn the amountReturn to set
     */
    public void setAmountReturn(double amountReturn) {
        this.amountReturn = amountReturn;
    }

    /**
     * @return the cashCashierId
     */
    public long getCashCashierId() {
        return cashCashierId;
}

    /**
     * @param cashCashierId the cashCashierId to set
     */
    public void setCashCashierId(long cashCashierId) {
        this.cashCashierId = cashCashierId;
    }

    /**
     * @return the typeSistemPayment
     */
    public int getTypeSistemPayment() {
        return typeSistemPayment;
    }

    /**
     * @param typeSistemPayment the typeSistemPayment to set
     */
    public void setTypeSistemPayment(int typeSistemPayment) {
        this.typeSistemPayment = typeSistemPayment;
    }

}

