/* Generated by Together */

package com.dimata.aiso.form.jurnal;

// import javax

import javax.servlet.http.*;

import com.dimata.qdep.form.FRMHandler;
import com.dimata.qdep.form.I_FRMInterface;
import com.dimata.qdep.form.I_FRMType;

// import aiso
import com.dimata.aiso.entity.jurnal.*;

public class FrmJurnalUmum extends FRMHandler implements I_FRMInterface, I_FRMType {
    public static final String FRM_JURNAL_UMUM = "JURNAL_UMUM";
    public static final int FRM_CLIENTID = 0;
    public static final int FRM_TGLTRANSAKSI = 1;
    public static final int FRM_KETERANGAN = 2;
    public static final int FRM_BOOK_TYPE = 3;
    public static final int FRM_YEARPERIODE = 4;
    public static final int FRM_CURR_TYPE = 5;
    public static final int FRM_REFERENCE_DOC = 6;
    public static final int FRM_JOURNAL_TYPE = 7;
    public static final int FRM_SHARED_TRANSACTION = 8;
    public static final int FRM_CONTACT_ID = 9;
    public static final int FRM_DEPARTMENT_ID = 10;

    public static String[] fieldNames =
            {
                "CLIENT_ID",
                "TGL_TRANSAKSI",
                "KETERANGAN",
                "BOOK_TYPE",
                "YEAR_PERIOD",
                "CURR_TYPE",
                "REFERENCE_DOC",
                "JOURNAL_TYPE",
                "SHARED_TRANSACTION",
                "FRM_CONTACT_ID",
                "FRM_DEPARTMENT_ID"
            };

    public static int[] fieldTypes =
            {
                TYPE_LONG,
                TYPE_DATE,
                TYPE_STRING + ENTRY_REQUIRED,
                TYPE_LONG,
                TYPE_STRING,
                TYPE_LONG,
                TYPE_STRING,
                TYPE_INT,
                TYPE_INT,
                TYPE_LONG,
                TYPE_LONG
            };

    private JurnalUmum jurnalumum;


    /** Creates new FrmPerkiraan */
    public FrmJurnalUmum(JurnalUmum jurnalumum) {
        this.jurnalumum = jurnalumum;
    }


    public FrmJurnalUmum(HttpServletRequest request, JurnalUmum jurnalumum) {
        super(new FrmJurnalUmum(jurnalumum), request);
        this.jurnalumum = jurnalumum;
    }

    public String getFormName() {
        return FRM_JURNAL_UMUM;
    }

    public int[] getFieldTypes() {
        return fieldTypes;
    }

    public String[] getFieldNames() {
        return fieldNames;
    }


    public int getFieldSize() {
        return fieldNames.length;
    }


    public JurnalUmum getEntityObject() {
        return jurnalumum;
    }


    public void requestEntityObject(JurnalUmum jurnalumum) {
        try {
            this.requestParam();
            jurnalumum.setTglTransaksi(this.getDate(FRM_TGLTRANSAKSI));
            jurnalumum.setKeterangan(this.getString(FRM_KETERANGAN));
            jurnalumum.setBookType(this.getLong(FRM_BOOK_TYPE));
            jurnalumum.setCurrType(this.getLong(FRM_CURR_TYPE));
            jurnalumum.setReferenceDoc(this.getString(FRM_REFERENCE_DOC));
            jurnalumum.setJurnalType(this.getInt(FRM_JOURNAL_TYPE));
            jurnalumum.setIShareTransaction(this.getInt(FRM_SHARED_TRANSACTION));
            jurnalumum.setContactOid(this.getLong(FRM_CONTACT_ID));
            jurnalumum.setDepartmentOid(this.getLong(FRM_DEPARTMENT_ID));
            this.jurnalumum = jurnalumum;
        } catch (Exception e) {
            jurnalumum = new JurnalUmum();
        }
    }

}
