/* Generated by Together */



package com.dimata.qdep.db;



public interface I_DBInterface {

    

    public int getFieldSize();

    public String getTableName();

    public String[] getFieldNames();

    public int[] getFieldTypes();

    

    public String getPersistentName();

    

}

